Add Native FileList
instructure/canvas-ios pull request #1520
Opened 2020-09-03 22:31 UTC by vanwagonet

This is still behind a flag, and tests for adding new files will be later.

refs: MBL-14705
affects: none
release note: none

2020-09-03 22:35 UTC, vanwagonet commented on Core/Core/Conversations/AttachmentCardsViewController.swift
> +                card.updateFile(name: NSLocalizedString("Failed. Tap for options", bundle: .core, comment: ""), icon: .warningLine)
I just noticed that these strings don't use .core & should.

2020-09-03 22:35 UTC, vanwagonet commented on Core/Core/Files/APIFile.swift
> +        throw NSError.instructureError("Not for actual api encoding")
We shouldn't use `APIFolderItem` as a `Response` type, but it need to be `Codable` for the use case to use it.

2020-09-03 22:35 UTC, vanwagonet commented on Core/Core/Files/APIFile.swift
> +    let size: Int?
I got a crash because a file didn't have a size.

2020-09-03 22:35 UTC, vanwagonet commented on Core/Core/Files/FileEditor/FileEditorView.swift
> +import SwiftUI
This file isn't really ready, but since it's behind a flag I left it in rather than try to fix routing.

2020-09-03 22:41 UTC, inst-danger commented
<!-- build-link-magic-string: 4fed8cd59bfa480fac4808d916d08862 eda1763be30f4b1499d9ec90caf7d7ad 200aafecb949421fb512520263db85d8 -->
## Latest Installable Builds

(will redirect to this page if no builds exist yet)
student: [Link](https://rebrand.ly/1p69lir) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2F1p69lir)
teacher: [Link](https://rebrand.ly/g054c0g) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Fg054c0g)
parent: [Link](https://rebrand.ly/tdp2k2n) | [QR](https://qr.rebrandly.com/v1/qrcode?shortUrl=rebrand%2Ely%2Ftdp2k2n)

2020-09-03 22:43 UTC, inst-danger reviewed
fix lint

2020-09-03 22:43 UTC, inst-danger commented on Core/CoreTests/Files/FileLIst/FileListViewControllerTests.swift
> +            .make(thumbnail_url: URL(string: "/"))
```suggestion
            .make(thumbnail_url: URL(string: "/")),
```

2020-09-03 23:03 UTC, inst-danger reviewed
fix lint

2020-09-03 23:03 UTC, inst-danger commented on Core/CoreTests/Files/FileLIst/FileListViewControllerTests.swift
> +            .make(thumbnail_url: URL(string: "/"))
```suggestion
            .make(thumbnail_url: URL(string: "/")),
```

2020-09-03 23:33 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.07% | 93.17% | -0.1%

[MBL-14705](https://instructure.atlassian.net/browse/MBL-14705)

#### Affected Apps: None
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2020-09-04 07:38 UTC, laura-quijada commented
Not interested

2020-09-04 17:15 UTC, cobbal requested changes
Opening an empty folder doesn't properly display empty view until refresh, and then when you hit back the folder is gone from the parent folder until you refresh.

2020-09-04 17:15 UTC, cobbal commented on Core/CoreTests/Files/FileLIst/FileListViewControllerTests.swift
> +//
weird caps in `FileLIst`

2020-09-04 19:58 UTC, vanwagonet commented on Core/CoreTests/Files/FileLIst/FileListViewControllerTests.swift
> +//
k, will fix.

2020-09-08 14:29 UTC, cobbal approved these changes

2020-09-08 15:17 UTC, merged