Use symbols for icons in SwiftUI
instructure/canvas-ios pull request #1532
Opened 2020-09-14 15:42 UTC by cobbal

[ignore-commit-lint]

2020-09-14 16:16 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49432444/p/066a118b26928f4209e57368f59fde43">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/49432444/p/066a118b26928f4209e57368f59fde43" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49432453/p/e32652d3b3d8e1a39ce2c5b971f40948">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/49432453/p/e32652d3b3d8e1a39ce2c5b971f40948" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/49432426/p/966c13e6ad518bcde3a3cee471d61681">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/49432426/p/966c13e6ad518bcde3a3cee471d61681" />
  </a>
</details>

2020-09-14 19:54 UTC, inst-danger commented
<!--
  4 failure:  One or more files..., Please add a refe..., Please add which ..., Please add a rele...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a reference to a jira ticket. For example: `refs: MBL-10023`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add which apps this change affects. Example: `affects: Teacher, Student` or `affects: none`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  </tbody>
</table>



Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.11% | 93.16% | -0.06%
Core/Core/SwiftUIViews/Icon.swift | 40% | -- | --
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2020-09-15 14:09 UTC, vanwagonet requested changes
Looks great, just one nitpick.

2020-09-15 14:09 UTC, vanwagonet commented on scripts/build-icons.js
> +`
Is this blank first line intentional? It shows up in each svg file. You can put a `.trimStart()` at the end to eliminate it. I think we want the trailing newline though.

2020-09-15 14:10 UTC, vanwagonet commented on scripts/build-icons.js
> +  <line id="right-margin"  x1="24" x2="24" y1="0" y2="24"/>
looks like there's an extra space after the id here. if you are trying to line things up you actually want the extra space after left-margin.

2020-09-15 19:34 UTC, vanwagonet approved these changes

2020-09-15 19:35 UTC, merged