Add Header to swiftGrader
instructure/canvas-ios pull request #1551
Opened 2020-09-22 21:07 UTC by vanwagonet

refs: MBL-14706
affects: Teacher
release note: none

2020-09-22 21:18 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  2 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


[MBL-14706](https://instructure.atlassian.net/browse/MBL-14706)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2020-09-22 21:50 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50289282/p/2fe1accb0d91e19fb7ebcd832b25fb84">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/50289282/p/2fe1accb0d91e19fb7ebcd832b25fb84" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50289290/p/748bb34361650c6923d1a97ad738236a">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/50289290/p/748bb34361650c6923d1a97ad738236a" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/50289262/p/20616ca3f99d350917affd9e0681958e">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/50289262/p/20616ca3f99d350917affd9e0681958e" />
  </a>
</details>

2020-09-23 22:17 UTC, armstrongnate requested changes
Code looks good. Getting a crash on first launch of speed grader (video sent via slack). I hope it's not an issue with the ForEach still. 😬

2020-09-24 15:59 UTC, armstrongnate approved these changes

2020-09-24 16:22 UTC, merged