Remove keyboardspace
instructure/canvas-ios pull request #1573
Opened 2020-10-05 14:40 UTC by balintbartok

refs: refs: MBL-14802
affects: Student, Teacher
release note: Fix extra space above keyboard when replying to discussion

2020-10-05 15:05 UTC, inst-danger commented
<!--
  0 failure: 
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-default;
-->



Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 93.08% | 93.08% | 0%

[MBL-14802](https://instructure.atlassian.net/browse/MBL-14802)

#### Affected Apps: Student, Teacher

#### Release Note: 
Fix extra space above keyboard when replying to discussion
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2020-10-05 15:06 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/51612433/p/5e280e17e59e94e7c06773c6f5aba93c">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/51612433/p/5e280e17e59e94e7c06773c6f5aba93c" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/51612453/p/08d849f44ce64e92b92975d87a718619">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/51612453/p/08d849f44ce64e92b92975d87a718619" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/51612367/p/28ca0cc947012e76bb2371a957c58738">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/51612367/p/28ca0cc947012e76bb2371a957c58738" />
  </a>
</details>

2020-10-05 16:13 UTC, vanwagonet requested changes
I think a better solution to this problem is a check in KeyboardTransitioning for iOS 14, which then will skip updating the constraint.

2020-10-05 16:13 UTC, vanwagonet commented on Core/Core/Discussions/DiscussionReplyViewController.swift
> +        keyboard = KeyboardTransitioning(view: view, space: nil)
The keyboardSpace is necessary in iOS 13, because the safe area does not end up including the keyboard.

2020-10-05 18:54 UTC, balintbartok commented
> I think a better solution to this problem is a check in KeyboardTransitioning for iOS 14, which then will skip updating the constraint.

Hmm.. I don't think that's the case, this is still needed in 14, I can confirm that after some testing. The problem is, that this particular modal is not full screen, but "formsheet size", and the keyboard space constraint was designed for full screens. So what happens is the space is applied (proportionally) on the smaller modal.. I'll keep looking into a solution

2020-10-05 22:42 UTC, balintbartok commented
so it turns out the problem was the modal view being shifted up a little on ipad, due to the keyboard appearing on the bottom. the whole calculation was done after the keyboardwillshow, so it had to be switched to keyboarddidshow in order to use the right layout.

2020-10-07 16:10 UTC, vanwagonet approved these changes
This seems to improve the situation, but I'm still getting cases where I end up with 2 scrollbars or it otherwise gets messed up. I think it's worth merging this small change & we can look later at fixing additional scrollbar issues.

2020-10-07 16:19 UTC, merged