Make grade circle color reflect the course color.
instructure/canvas-ios pull request #1598
Opened 2020-10-15 13:29 UTC by Attila-Varga-Instructure

refs: MBL-14830
affects: Student
release note: Make grade circle color reflect the course color.

test plan:
- Have a graded submission as a student on a points assignment.
- View the assignment as the student.
- The colored portion of the grade circle should be the course color.

2020-10-15 13:57 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52719394/p/16c5f77fa84afc5cb482e0797709bc1a">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/52719394/p/16c5f77fa84afc5cb482e0797709bc1a" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52719413/p/475fc42e10422ebc7155e313610bfd13">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/52719413/p/475fc42e10422ebc7155e313610bfd13" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/52719386/p/c1258e273965559b25a3f7dca3242ab9">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/52719386/p/c1258e273965559b25a3f7dca3242ab9" />
  </a>
</details>

2020-10-15 14:01 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/APITodoTests/testDeleteTodoRequest</summary>


    Assertion Failure at APITests.swift:320: XCTAssertNotNil failed
</details>
<details><summary>:x: XCTest failed: CoreTests/PersistencyTests/testAddToQueue</summary>


    Assertion Failure at PersistencyTests.swift:61: Asynchronous wait failed: Exceeded timeout of 0.5 seconds, with unfulfilled expectations: "expectation".
</details>


[MBL-14830](https://instructure.atlassian.net/browse/MBL-14830)

#### Affected Apps: Student

#### Release Note: 
Make grade circle color reflect the course color.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2020-10-15 14:51 UTC, vanwagonet commented on Core/Core/UIViews/GradeCircleView.swift
> +            gradeCircle.color = circleColor
If you set `gradeCircle.color = nil`, it will use the inherited `tintColor`. But this doesn't seem to invasive either, so I'm good either way.

2020-10-15 14:53 UTC, vanwagonet requested changes
The checkmark in the center of the circle is still using the brand primary color instead of the context color. It looks really odd to have the circle & checkmark different colors.

2020-10-16 14:19 UTC, vanwagonet approved these changes
QA+1 nice!

2020-10-16 17:46 UTC, merged