Check if group has an active course
instructure/canvas-ios pull request #1922
Opened 2021-08-06 09:22 UTC by balintbartok

refs: MBL-15548
affects: Student
release note: Fixed groups showing for inactive courses

test plan: see ticket, check normal groups with own account

2021-08-06 09:46 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/85955774/p/daa3c43834ea3afd0f0e52813f2e14c0">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/85955774/p/daa3c43834ea3afd0f0e52813f2e14c0" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/85955781/p/8c3dd65f9b47e177b6bbdbaacdc4c920">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/85955781/p/8c3dd65f9b47e177b6bbdbaacdc4c920" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/85955727/p/6904e3afc55e5335627ea0276a2692a6">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/85955727/p/6904e3afc55e5335627ea0276a2692a6" />
  </a>
</details>

2021-08-06 09:46 UTC, inst-danger commented
<!--
  0 failure: 
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-default;
-->



Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.01% | 91.98% | 0.03%

[MBL-15548](https://instructure.atlassian.net/browse/MBL-15548)

#### Affected Apps: Student

#### Release Note: 
Fixed groups showing for inactive courses
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2021-08-11 07:39 UTC, vargaat requested changes

2021-08-11 07:39 UTC, vargaat commented on Core/Core/Groups/Group.swift
> +        courseID == nil || getCourse() != nil
If `getCourse()` returns an instance, would it be possible to check that course's state? If I navigate to `All courses` go back and do a pull-to-refresh the group still appears for a moment.

https://user-images.githubusercontent.com/72396990/128989141-f4c767b6-78cd-4264-bd66-0ad8c161ac29.MP4

2021-08-13 06:39 UTC, davidvarga93 approved these changes
QA+1

2021-08-13 07:13 UTC, vargaat approved these changes
QA+1

2021-08-13 07:17 UTC, idevainstr approved these changes
QA+1

2021-08-13 12:31 UTC, merged