Introduce K5 capability for E2E Student
instructure/canvas-ios pull request #1924
Opened 2021-08-11 12:04 UTC by davidvarga93

refs: MBL-15378
affects: Student
release note: none

test plan:

2021-08-11 12:22 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  2 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


[MBL-15378](https://instructure.atlassian.net/browse/MBL-15378)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2021-08-11 13:07 UTC, vargaat requested changes

2021-08-11 13:07 UTC, vargaat commented on Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
> -        }
The project needs this package.

2021-08-11 14:09 UTC, vargaat requested changes
Seems like the TestFoundation project file is damaged.

`<IDEFileReference, 0x7ff6de743020: name:TestsFoundation path:group:TestsFoundation/TestsFoundation.xcodeproj> Failed to load container at path: /Users/vagrant/git/TestsFoundation/TestsFoundation.xcodeproj, Error: Error Domain=Xcode3ProjectErrorDomain Code=2 "The project ‘TestsFoundation’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
`

2021-08-12 08:58 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/86660872/p/b6a23a514bc0529b96d1893bfb02f3ab">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/86660872/p/b6a23a514bc0529b96d1893bfb02f3ab" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/86660877/p/f5165278ee64afc8aed224622f43b5d0">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/86660877/p/f5165278ee64afc8aed224622f43b5d0" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/86660869/p/8864012f82d52a2061365d1cf1f93a27">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/86660869/p/8864012f82d52a2061365d1cf1f93a27" />
  </a>
</details>

2021-08-12 09:53 UTC, davidvarga93 commented
Nightly:
https://app.bitrise.io/build/651cff96-373a-4cfe-95b5-0ede997e148f#?tab=log

2021-08-12 11:38 UTC, vargaat approved these changes

2021-08-12 11:53 UTC, idevainstr approved these changes

2021-08-12 12:45 UTC, davidvarga93 commented
K5StudentE2ETests
    ✔ testK5Reset (16.897 seconds)
    ✔ testStudentK5 (16.749 seconds)

2021-08-13 07:08 UTC, merged