Comment library
instructure/canvas-ios pull request #2088
Opened 2022-02-14 11:48 UTC by idevainstr

refs: MBL-15821
affects: Teacher
release note: Comment library is now available for submission comments.
test plan: see ticket

2022-02-14 12:08 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  One or more files...
  
  4 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.42% | 91.44% | -0.02%
Core/Core/Extensions/SwiftUIExtensions.swift | 27.27% | 50% | -22.73%

[MBL-15821](https://instructure.atlassian.net/browse/MBL-15821)

#### Affected Apps: Teacher

#### Release Note: 
Comment library is now available for submission comments.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-02-14 12:11 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/artifact/113042460/p/52509497a34ef55de7ddfa982af4b7da">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/113042460/p/52509497a34ef55de7ddfa982af4b7da" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/artifact/113042507/p/ac6b45be876aa96eae8096461f8a279d">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/113042507/p/ac6b45be876aa96eae8096461f8a279d" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/artifact/113042382/p/403f33b8926c8a1b5dfba8adbe4ac645">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/artifact/113042382/p/403f33b8926c8a1b5dfba8adbe4ac645" />
  </a>
</details>

2022-02-14 16:24 UTC, vargaat requested changes

2022-02-14 16:24 UTC, vargaat commented on rn/Teacher/ios/Teacher/SpeedGrader/ViewModel/SubmissionCommentLibraryViewModel.swift
> +    @Published var comments: [LibraryComment] = []
Shouldn't we have a loading state here? We know that lot of our users have poor connectivity. The page says "No suggestions available" while loading.

2022-02-14 16:24 UTC, vargaat commented on rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift
> +        self.settings = AppEnvironment.shared.subscribe(GetUserSettings(userID: "self"))
Shouldn't we refresh this setting? This will just read from core data but won't check for changes even if the cache had already expired.

2022-02-14 16:24 UTC, vargaat commented on rn/Teacher/ios/Teacher/SpeedGrader/ViewModel/SubmissionCommentLibraryViewModel.swift
> +        env.api.makeRequest(requestable, refreshToken: true) { response, _, _  in
Why we force a token refresh?

2022-02-15 08:58 UTC, balintbartok requested changes
there's a crash on iOS14, when you are entering 3+ characters into the text field

2022-02-18 12:45 UTC, vargaat requested changes
Seems like there's a glitch with filtering:
- Tap comment text box
- Library shows, pick a suggestion
- Library disappears, delete the inserted suggestion from the text box
- Tap text box again to bring up the library
- Only the comment I selected is visible

A11y issues:
- Library can't be triggered with voiceover, it just sees the text field
- Focusing on the close button in the library reads: x-line button

2022-02-21 08:37 UTC, davidvarga93 submitted a review, later dismissed
QA + 1

2022-02-21 08:43 UTC, balintbartok submitted a review, later dismissed
QA + 1

2022-02-21 10:25 UTC, vargaat approved these changes
QA+1

2022-02-21 10:26 UTC, merged