Profile screen opened from SpeedGrader comments has no close nor send buttons
instructure/canvas-ios pull request #2117
Opened 2022-03-25 16:14 UTC by idevainstr

refs: MBL-15946
affects: Teacher
release note: Fixed profile screen top buttons in SpeedGrader comments.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/160158638-4aa50fc8-8a6c-4722-9765-8ee29c25a059.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/160158645-ac0ca8e5-a69b-4561-9181-c492e86e2979.png"></td>
</tr>
</table>

2022-03-25 16:28 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/011485a4-36e0-48d9-8450-a9ec21474dde/artifact/9991fc92c9b9cec1/p/2dcb539b6d615c0e63f5da4819f49523">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/011485a4-36e0-48d9-8450-a9ec21474dde/artifact/9991fc92c9b9cec1/p/2dcb539b6d615c0e63f5da4819f49523" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/011485a4-36e0-48d9-8450-a9ec21474dde/artifact/81312ccdde274260/p/383d89a9bebafb99c97b42a9e17a5573">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/011485a4-36e0-48d9-8450-a9ec21474dde/artifact/81312ccdde274260/p/383d89a9bebafb99c97b42a9e17a5573" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/011485a4-36e0-48d9-8450-a9ec21474dde/artifact/4f1524f3dfd1ea7d/p/fb9f064ccba9b2d2c2e549ca21fd9455">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/011485a4-36e0-48d9-8450-a9ec21474dde/artifact/4f1524f3dfd1ea7d/p/fb9f064ccba9b2d2c2e549ca21fd9455" />
  </a>
</details>

2022-03-25 16:37 UTC, inst-danger commented
<!--
  0 failure: 
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-default;
-->



Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.43% | 91.46% | -0.03%

[MBL-15946](https://instructure.atlassian.net/browse/MBL-15946)

#### Affected Apps: Teacher

#### Release Note: 
Fixed profile screen navigation bar items in SpeedGrader comments.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-03-28 07:37 UTC, idevainstr commented on Core/Core/People/ContextCard/Course/ContextCardView.swift
> -                Image.emailLine.foregroundColor(.textLightest)
I tried that first, but it didn't set because of the view wrapper probably.

2022-03-28 07:54 UTC, vargaat requested changes
For some reason the mail button on my account is still invisible, running on an iPhone SE with iOS 15.1.
<img src="https://user-images.githubusercontent.com/72396990/160351610-b3cc4221-c956-460e-90ce-055ac8673570.PNG" width=50% height=50%>

2022-03-29 12:04 UTC, vargaat approved these changes
QA+1

2022-03-29 12:44 UTC, balintbartok approved these changes
QA + 1

2022-03-29 12:44 UTC, merged