Added some more DataSeeding based tests, disabled the old ones
instructure/canvas-ios pull request #2120
Opened 2022-03-30 07:54 UTC by davidvarga93

refs: MBL-15484
affects: Teacher
release note: none

test plan:

2022-03-30 08:20 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.15% | 91.14% | 0.01%

[MBL-15484](https://instructure.atlassian.net/browse/MBL-15484)

#### Affected Apps: Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-03-30 08:39 UTC, davidvarga93 commented
![Screenshot 2022-03-30 at 10 39 30](https://user-images.githubusercontent.com/73543116/160789296-a8306852-df61-4109-b017-2eacb2fc2970.png)

2022-03-30 09:04 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/e60cfc5e-666e-41a3-856e-980f5d6466e9/artifact/efc6b31d18b97893/p/eccb2b5a6bedfad4bb602c5921e2d479">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/e60cfc5e-666e-41a3-856e-980f5d6466e9/artifact/efc6b31d18b97893/p/eccb2b5a6bedfad4bb602c5921e2d479" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/e60cfc5e-666e-41a3-856e-980f5d6466e9/artifact/48d60cfe5a96ebc5/p/673a1ac33ae47cf8d2cef0b999b006b4">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/e60cfc5e-666e-41a3-856e-980f5d6466e9/artifact/48d60cfe5a96ebc5/p/673a1ac33ae47cf8d2cef0b999b006b4" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/e60cfc5e-666e-41a3-856e-980f5d6466e9/artifact/31e6e0dcb24bb1de/p/28051f140073a6fac5cfe1c489f25fc6">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/e60cfc5e-666e-41a3-856e-980f5d6466e9/artifact/31e6e0dcb24bb1de/p/28051f140073a6fac5cfe1c489f25fc6" />
  </a>
</details>

2022-03-30 10:07 UTC, balintbartok submitted a review, later dismissed

2022-03-31 10:20 UTC, vargaat requested changes

2022-03-31 10:20 UTC, vargaat commented on rn/Teacher/ios/TeacherE2ETests/Assignments/DSContextCardE2ETests.swift
> +        let submission = seeder.createSubmission(courseId: course.id, assignmentId: assignment.id, requestBody:
These lines generate a lot of compiler warnings.

2022-03-31 10:20 UTC, vargaat commented on rn/Teacher/ios/TeacherE2ETests/Assignments/DSTodosE2ETests.swift
> +
Empty line could be removed.

2022-04-04 09:37 UTC, vargaat approved these changes

2022-04-05 08:38 UTC, idevainstr approved these changes

2022-04-05 10:06 UTC, merged