Add event name to the accessibility label of checkboxes in K5 Schedule
instructure/canvas-ios pull request #2147
Opened 2022-04-26 09:18 UTC by idevainstr

refs: MBL-15968
affects: Student
release note: none
test plan: see ticket

2022-04-26 09:37 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/c658be15-8472-4241-b050-e9a5290981e4/artifact/b16764f8ff891022/p/9dabe42dfbd79ac8e87b52d1ff0aa4a3">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/c658be15-8472-4241-b050-e9a5290981e4/artifact/b16764f8ff891022/p/9dabe42dfbd79ac8e87b52d1ff0aa4a3" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/c658be15-8472-4241-b050-e9a5290981e4/artifact/0b6c087ed628dca0/p/0ed17ea57127cb85fdaf91bd6f8f6273">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/c658be15-8472-4241-b050-e9a5290981e4/artifact/0b6c087ed628dca0/p/0ed17ea57127cb85fdaf91bd6f8f6273" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/c658be15-8472-4241-b050-e9a5290981e4/artifact/0b00f27c34f0727f/p/b6b6aed8999176f14b22bbb752e7191a">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/c658be15-8472-4241-b050-e9a5290981e4/artifact/0b00f27c34f0727f/p/b6b6aed8999176f14b22bbb752e7191a" />
  </a>
</details>

2022-04-26 09:39 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.82% | 91.82% | -0%

[MBL-15968](https://instructure.atlassian.net/browse/MBL-15968)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-04-28 08:17 UTC, vargaat requested changes

2022-04-28 08:17 UTC, vargaat commented on Core/Core/Dashboard/K5/View/Schedule/K5ScheduleEntryView.swift
> +        .accessibility(label: Text(viewModel.title) + Text(",") + Text("Mark item as done", bundle: .core))
We don't want that comma to get translated so let's use `Text(verbatim: ",")` instead.

2022-04-28 08:20 UTC, vargaat commented on Core/Core/Dashboard/K5/View/Schedule/K5ScheduleEntryView.swift
> +        .accessibility(label: Text(viewModel.title) + Text(",") + Text("Mark item as done", bundle: .core))
```suggestion
        .accessibility(label: Text(viewModel.title) + Text(verbatim: ",") + Text("Mark item as done", bundle: .core))
```

2022-04-28 10:29 UTC, vargaat approved these changes
QA+1

2022-05-02 07:42 UTC, merged