The app shows the illussion that you can star/favorite soft concluded courses
instructure/canvas-ios pull request #2154
Opened 2022-05-04 11:57 UTC by idevainstr

refs: MBL-16024
affects: Student
release note: Fixed past courses could have been favorited.
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/166676585-275d1c3c-37f9-49a7-8d69-0897c7cc98c9.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/166676588-2715ffae-f9c9-4e46-b100-2b7ed54876d5.png"></td>
</tr>
</table>

2022-05-04 12:10 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/93ca38ac-6037-46b6-962b-7b9b1c05ff10/artifact/e687959918c21a20/p/14fe320bb4ca4943fee14b953c580cea">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/93ca38ac-6037-46b6-962b-7b9b1c05ff10/artifact/e687959918c21a20/p/14fe320bb4ca4943fee14b953c580cea" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/93ca38ac-6037-46b6-962b-7b9b1c05ff10/artifact/c732e7b130257852/p/3aa2a59943ac30e334b559df13649ffb">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/93ca38ac-6037-46b6-962b-7b9b1c05ff10/artifact/c732e7b130257852/p/3aa2a59943ac30e334b559df13649ffb" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/93ca38ac-6037-46b6-962b-7b9b1c05ff10/artifact/45401b338cb32869/p/f7ec1188ddae9df559c890fe31fcabd6">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/93ca38ac-6037-46b6-962b-7b9b1c05ff10/artifact/45401b338cb32869/p/f7ec1188ddae9df559c890fe31fcabd6" />
  </a>
</details>

2022-05-04 12:14 UTC, inst-danger commented
<!--
  0 failure: 
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-default;
-->



Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.8% | 91.8% | 0%

[MBL-16024](https://instructure.atlassian.net/browse/MBL-16024)

#### Affected Apps: Student

#### Release Note: 
Fixed past courses could have been favorited.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-05-09 09:07 UTC, vargaat requested changes

2022-05-09 09:09 UTC, vargaat commented on Core/Core/Courses/Course.swift
> +            item.sections?.first(where: { $0.end_at ?? .distantFuture < Clock.now }) != nil
Also the logic in `CourseSectionStatus` also seems to be faulty since it checks the last section of the user but doesn't iterate through them.

2022-05-11 09:34 UTC, closed without merging