Changed cell divider to edge to edge and the selection indicator
instructure/canvas-ios pull request #2159
Opened 2022-05-09 14:39 UTC by tamasiscoming

refs: MBL-16052
affects: Student, Teacher, Parent
release note: none
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/167433287-5e6a409e-3119-479c-a413-897fd1c3e387.jpeg"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/168573571-7dae3299-4b5f-4cdf-912a-a4f93e83391e.png"></td>
</tr>
</table>

2022-05-09 14:47 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/31624df7-deff-4e32-94cf-a1eaca95f531/artifact/9893648346634b83/p/8787b10fef36068230e4746054993056">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/31624df7-deff-4e32-94cf-a1eaca95f531/artifact/9893648346634b83/p/8787b10fef36068230e4746054993056" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/31624df7-deff-4e32-94cf-a1eaca95f531/artifact/eea2578879f24d48/p/7ef469c890934b1ee43fda07aab0eb5f">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/31624df7-deff-4e32-94cf-a1eaca95f531/artifact/eea2578879f24d48/p/7ef469c890934b1ee43fda07aab0eb5f" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/31624df7-deff-4e32-94cf-a1eaca95f531/artifact/ed8aca3179af95f1/p/d093734d42f3d365c593eba483e075d6">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/31624df7-deff-4e32-94cf-a1eaca95f531/artifact/ed8aca3179af95f1/p/d093734d42f3d365c593eba483e075d6" />
  </a>
</details>

2022-05-10 09:47 UTC, vargaat requested changes
As we discussed, the selection indicator should fill the cell's total height.

2022-05-16 10:40 UTC, idevainstr approved these changes
QA+1

2022-05-16 13:50 UTC, vargaat approved these changes

2022-05-16 13:50 UTC, merged