Extend e2e tests with grade types
instructure/canvas-ios pull request #2167
Opened 2022-05-20 06:46 UTC by davidvarga93

refs: MBL-15950
affects: Student
release note: none

test plan:

2022-05-20 07:03 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/660dd5eb-7286-48ea-b11c-13c0a4aaf271/artifact/999467479933597e/p/cb7570ce6e96a348967c4d349a8a66f2">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/660dd5eb-7286-48ea-b11c-13c0a4aaf271/artifact/999467479933597e/p/cb7570ce6e96a348967c4d349a8a66f2" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/660dd5eb-7286-48ea-b11c-13c0a4aaf271/artifact/40311b2e38e1863a/p/6264ebdae771cf47e7f38202277b5c11">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/660dd5eb-7286-48ea-b11c-13c0a4aaf271/artifact/40311b2e38e1863a/p/6264ebdae771cf47e7f38202277b5c11" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/660dd5eb-7286-48ea-b11c-13c0a4aaf271/artifact/a80aecfd9db6226b/p/891399a0a03544c9eab29abcd02b2040">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/660dd5eb-7286-48ea-b11c-13c0a4aaf271/artifact/a80aecfd9db6226b/p/891399a0a03544c9eab29abcd02b2040" />
  </a>
</details>

2022-05-20 07:04 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/API/APIGraphQLRequestable.swift:28:38: Comma Inheritance Rule Violation: Use commas to separate types in inheritance lists (comma_inheritance)
    
    
</details>


[MBL-15950](https://instructure.atlassian.net/browse/MBL-15950)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-05-23 09:16 UTC, vargaat requested changes

2022-05-25 07:03 UTC, vargaat approved these changes

2022-05-25 07:59 UTC, balintbartok approved these changes

2022-05-25 08:06 UTC, merged