Course subpages list selection indicator
instructure/canvas-ios pull request #2181
Opened 2022-06-03 11:49 UTC by tamasiscoming

refs: MBL-16073
affects: Student, Teacher
release note: none
test plan: see ticket

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/171827172-308b7745-1515-4ab7-b5f7-e7db18634ab5.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/171827034-b7353011-bbd4-4216-a2b7-c210513b4bbc.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/171827339-5de47f09-3b1f-4851-9c04-87653b5c4f8c.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/171827307-b79e81ec-208b-4f38-882c-b66d5c2fbe82.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/171827342-fdfbccdb-05da-4275-9dc8-75293db4af83.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/171828108-0f90ae76-0c04-47c6-8d17-6d557b914c1c.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/171827343-d9c77ff6-8a6c-4e83-975c-466150ab878a.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/171827318-2871fe6b-09a3-4c58-bde6-bde8cf78cd6c.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/171827345-0f086341-4267-42fe-95c4-9d894cd89ee2.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/171827323-878290ed-4aae-4bd7-b5c6-ea9b23f9bb45.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/171827347-bd23d07a-cea5-433f-8df9-806d71bfdcb9.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/171827325-1343bc90-acff-465e-a9f4-9c8439c0b3fa.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/171827350-29e479ad-a0d0-4a1a-a67d-e0b15b21c484.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/171827330-33237db4-7139-4159-b094-3a2444ececdc.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/171827353-38bef6e3-d38c-4492-855f-f28ce0d651d2.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/171827332-85be55bb-812a-4782-ae97-62382ed9c5bb.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/171827354-95cb1779-1ecc-4c8a-a837-b8b91c750425.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/171827334-a06e2718-0951-4526-9f52-db444adb7145.PNG"></td>
</tr>
</table>

2022-06-03 12:15 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.85% | 91.85% | 0%

[MBL-16073](https://instructure.atlassian.net/browse/MBL-16073)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-06-03 12:48 UTC, vargaat requested changes
- Looks good! Kudos for the small refactors! 👍 
- Could you please also check the grades and the conferences lists as well if we can apply this indicator on those?
- I've left a few comments regarding naming and file placement, please check on those.

2022-06-03 12:48 UTC, vargaat commented on Core/Core/Modules/ModuleList/CustomCellBackgroundView.swift
> +public class CustomCellBackgroundView: UIView {
I would change this name to something more specific, it's just too generic for now. Its SwiftUI counterpart is named `ContextButton`, maybe we could name this similar to that e.g.: `ContextCellBackgroundView.`

2022-06-03 12:48 UTC, vargaat commented on Core/Core/Modules/ModuleList/CustomCellBackgroundView.swift
> +//
This file would be at a better place in `Core/UIViews` folder instead of the modules one.

2022-06-03 12:48 UTC, vargaat commented on rn/Teacher/ios/CustomBrandedView.xib
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Is this file being used or just a leftover?

2022-06-03 12:50 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/112c7a2f-68b8-4ec8-a119-22a8433d3331/artifact/6b6202167e61632d/p/c4d2242a26777f6e18ed2e8b3473f910">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/112c7a2f-68b8-4ec8-a119-22a8433d3331/artifact/6b6202167e61632d/p/c4d2242a26777f6e18ed2e8b3473f910" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/112c7a2f-68b8-4ec8-a119-22a8433d3331/artifact/734945bdc3e707f2/p/2e1facc5114c401fe73a030b5285155e">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/112c7a2f-68b8-4ec8-a119-22a8433d3331/artifact/734945bdc3e707f2/p/2e1facc5114c401fe73a030b5285155e" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/112c7a2f-68b8-4ec8-a119-22a8433d3331/artifact/c80d0c6624136796/p/876fe145b9f43a7883aa0c409e525b19">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/112c7a2f-68b8-4ec8-a119-22a8433d3331/artifact/c80d0c6624136796/p/876fe145b9f43a7883aa0c409e525b19" />
  </a>
</details>

2022-06-08 14:27 UTC, vargaat approved these changes
QA+1

2022-06-09 08:47 UTC, davidvarga93 approved these changes
QA + 1

2022-06-10 13:50 UTC, merged