Added E2E Test for Grading Standards
instructure/canvas-ios pull request #2183
Opened 2022-06-07 06:47 UTC by davidvarga93

refs: MBL-16088
affects: Student
release note: none

test plan:

2022-06-07 07:04 UTC, inst-danger commented
<!-- build-link-magic-string -->
<details><summary>Student.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/866911cc-f1df-4101-ae4a-d2765c329eb7/artifact/ff9431b6b40c1d55/p/a05105d34919870ada138c5311ac71fb">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/866911cc-f1df-4101-ae4a-d2765c329eb7/artifact/ff9431b6b40c1d55/p/a05105d34919870ada138c5311ac71fb" />
  </a>
</details>
<details><summary>Teacher.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/866911cc-f1df-4101-ae4a-d2765c329eb7/artifact/cedc7722c81fff16/p/0d98d65481dc2eb66f6b3d802083f3b0">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/866911cc-f1df-4101-ae4a-d2765c329eb7/artifact/cedc7722c81fff16/p/0d98d65481dc2eb66f6b3d802083f3b0" />
  </a>
</details>
<details><summary>Parent.ipa</summary>
  <a href="https://app.bitrise.io/app/88a3641e29e4745c/build/866911cc-f1df-4101-ae4a-d2765c329eb7/artifact/606ee68927d3305b/p/d1ce1804e12f0523dc926513b1476aba">
    <img src="https://api.qrserver.com/v1/create-qr-code/?data=https://app.bitrise.io/app/88a3641e29e4745c/build/866911cc-f1df-4101-ae4a-d2765c329eb7/artifact/606ee68927d3305b/p/d1ce1804e12f0523dc926513b1476aba" />
  </a>
</details>

2022-06-07 07:08 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/TestsFoundation/TestsFoundation/DataSeeding/Submissions/Grades/GradingStandard/CreateDSGradingStandardsRequest.swift:44:89: Trailing Comma Violation: Multi-line collection literals should have trailing commas. (trailing_comma)
    /Users/vagrant/git/Student/StudentE2ETests/Grades/DSGradingStandardsE2ETests.swift:58:1: error: Vertical Whitespace Violation: Limit vertical whitespace to a single empty line. Currently 2. (vertical_whitespace)
    
</details>


[MBL-16088](https://instructure.atlassian.net/browse/MBL-16088)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-06-07 07:40 UTC, davidvarga93 commented
<img width="419" alt="Screenshot 2022-06-07 at 9 40 35" src="https://user-images.githubusercontent.com/73543116/172323819-71342696-8e3e-43ad-a4cc-52146a4c38e2.png">

2022-06-08 10:09 UTC, vargaat requested changes

2022-06-08 10:09 UTC, vargaat commented on TestsFoundation/TestsFoundation/DataSeeding/Submissions/Grades/GradingStandard/CreateDSGradingStandardsRequest.swift
> +            GradeEntry.init(name: "A", value: 94), GradeEntry.init(name: "A-", value: 90),
`.init`s could be omitted.

2022-06-08 10:09 UTC, vargaat commented on TestsFoundation/TestsFoundation/DataSeeding/Submissions/Grades/GradingStandard/CreateDSGradingStandardsRequest.swift
> +    public var path: String
Is this modified from anywhere? If not, we could use `let` instead.

2022-06-08 10:09 UTC, vargaat commented on TestsFoundation/TestsFoundation/DataSeeding/Course/CreateDSCourseRequest.swift
> +struct UpdateDSCourseRequest: APIRequestable {
If these are about updates would it make sense to create an `UpdateDScourseRequest.swift` file for them?

2022-06-10 07:25 UTC, vargaat approved these changes

2022-06-10 13:51 UTC, merged