New File Submission Service For Share Extension
instructure/canvas-ios pull request #2255
Opened 2022-09-12 15:09 UTC by vargaat

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Approve from product or not needed

refs: MBL-16145
affects: Student
release note: none
test plan: Try to break file upload when submitting via file extension submission. Background upload is only supported when the dismiss button appears during upload.

2022-09-12 15:31 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


<details><summary>:x: XCTest failed: CoreTests/BackgroundURLSessionProviderTests/testCreatesNewSessionIfSessionBecameInvalid</summary>


    Assertion Failure at BackgroundURLSessionProviderTests.swift:62: XCTAssertNotEqual failed: ("<__NSURLBackgroundSession: 0x7f9c51ab8300>") is equal to ("<__NSURLBackgroundSession: 0x7f9c51ab8300>")
</details>


[MBL-16145](https://instructure.atlassian.net/browse/MBL-16145)

#### Affected Apps: Student
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-09-13 13:59 UTC, szabolcs-instructure approved these changes
QA + 1
I mostly had cosmetic remarks only

2022-09-13 13:59 UTC, szabolcs-instructure commented on Core/CoreTests/Files/FileSubmission/Model/BinaryUpload/BackgroundURLSessionProviderTests.swift
> +    }
Just to be super safe maybe we could set `testee` and `mockUploadProgressObserversCache` to nil in the `tearDown` function

2022-09-13 14:47 UTC, vargaat commented on Core/Core/Files/FileSubmission/Model/BinaryUpload/FileUploadProgressObserversCache.swift
> +    public func retrieveProgressObserver(fileUploadItemID: NSManagedObjectID, fileSubmissionID: NSManagedObjectID) -> FileUploadProgressObserver {
I also made `makeObjectID` function private.

2022-09-13 15:33 UTC, vargaat commented on Core/Core/Files/FileSubmission/Model/BinaryUpload/FileUploadProgressObserversCache.swift
> +    private func retrieveProgressObserver(taskID: String?) -> FileUploadProgressObserver? {
Refactored.

2022-09-14 11:11 UTC, idevainstr requested changes
just some minors...

2022-09-16 08:55 UTC, vargaat commented on Core/Core/Files/FileSubmission/Model/BinaryUpload/FileUploadProgressObserver.swift
> +                  let self = self
Actually this `performAndWait` accepts a non-escaping block so we don't need this `[weak self]` at all.

2022-09-16 08:55 UTC, vargaat commented on Core/Core/Files/FileSubmission/Model/Entities/FileSubmissionErrors.swift
> +        case notReady
Agree, renamed.

2022-09-19 08:03 UTC, szabolcs-instructure approved these changes

2022-09-19 10:47 UTC, idevainstr approved these changes
QA +1 🏅

2022-09-19 11:56 UTC, davidvarga93 approved these changes
QA + 1

2022-09-19 12:01 UTC, balintbartok approved these changes
QA + 1

2022-09-19 12:25 UTC, merged