Fix add comment field on share extension
instructure/canvas-ios pull request #2288
Opened 2022-10-20 12:23 UTC by szabolcs-instructure

refs: MBL-16316
affects: Student
release note: Fix voice over for add comment text in share extension

test plan: see ticket

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Approve from product or not needed

2022-10-24 09:20 UTC, idevainstr submitted a review, later dismissed
QA +1 iOS 14.8.1, iPadOS 16.1b

2022-10-27 08:19 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  One or more files...
  
  4 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.67% | 91.67% | 0%
Core/Core/Submissions/SubmissionBreakdown/SubmissionBreakdownViewModelProtocol.swift | 0% | 0% | 0%
Core/Core/Quizzes/QuizDetails/ViewModel/PreviewQuizDetailsViewModel.swift | 0% | 0% | 0%

[MBL-16316](https://instructure.atlassian.net/browse/MBL-16316)

#### Affected Apps: Student

#### Release Note: 
Fix voice over for add comment text in share extension
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-10-27 08:23 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Fde6a593e-b433-4c09-8037-12f5ae452262%2Fartifact%2F0e17fe0ab32723f7%2Fp%2Fe77f61be78f0d0f209adbfa87a323827&size=150x150" />
</details>


<!-- StudentBuild -->

2022-10-27 08:26 UTC, vargaat approved these changes
QA+1

2022-10-27 08:26 UTC, merged

2022-10-27 08:27 UTC, vargaat requested changes

2022-10-27 08:27 UTC, vargaat commented on Core/Core/SubmitAssignmentExtension/View/SubmitAssignmentExtensionView.swift
> +            .accessibilityLabel("Add optional comment")
This should be a localized string.