RCE content theme switcher 🎄
instructure/canvas-ios pull request #2325
Opened 2022-12-13 14:53 UTC by idevainstr

refs: MBL-16352
affects: Student, Teacher, Parent
release note: Added an appearance switcher in dark mode for html content.
test plan: See ticket.

## Screenshots

<table>
<tr><th>Dark</th><th>Light</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/207365605-59c43386-4873-418a-ae86-73cfd7679504.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/79920680/207365597-311b30c9-94ff-468e-93a2-c8e047022597.png" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product or not needed

2022-12-13 15:08 UTC, inst-danger commented
<details><summary>Parent Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F92ef21e0-7582-4eea-b728-cabf6038efbb%2Fartifact%2F46c5a87d28717d4f%2Fp%2Fe742714df2da7c53cbbd43fe94a24406&size=150x150" />
</details>


<!-- ParentBuild -->

2022-12-13 15:29 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F6dc1940f-07f7-4789-ad26-207140bdf3dc%2Fartifact%2Fef37199950811aa9%2Fp%2Fde1bb8b3f237f59dbcafe8f819b3cfa9&size=150x150" />
</details>


<!-- TeacherBuild -->

2022-12-13 15:30 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F7b447320-60ad-4f2d-9ae3-244235ee88ba%2Fartifact%2Fc1a0cf3829678ee7%2Fp%2Febe4ee40d74cdca401f87b4f9a2324cd&size=150x150" />
</details>


<!-- StudentBuild -->

2022-12-13 15:34 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Build failed, skipping coverage check
  </td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: StudentUnitTests/QuizDetailsViewControllerTests/testLayout</summary>


    Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x600000042440 "Student.CoreWebView:0x7feb77a12200.leading"> and <NSLayoutXAxisAnchor:0x600000042140 "UIView:0x7feb3729f7f0.leading"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal. (NSGenericException)
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/QuizDetailsViewControllerTests/testNoQuiz</summary>


    Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x600000044440 "Student.CoreWebView:0x7feb67198800.leading"> and <NSLayoutXAxisAnchor:0x600000072bc0 "UIView:0x7feb370d0170.leading"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal. (NSGenericException)
</details>


[MBL-16352](https://instructure.atlassian.net/browse/MBL-16352)

#### Affected Apps: Student, Teacher, Parent

#### Release Note: 
Added an appearance switcher in dark mode for html content.
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2022-12-15 15:00 UTC, szabinst requested changes
Not sure if we can fix it but when you change modes, the profile image reloads everytime. 
https://user-images.githubusercontent.com/110813321/207893291-c2b85ad8-8358-4f69-b139-28f420f92ef1.MP4

This one is an edge case, but if you open a page with dark mode, and switch the system theme to light mode then part of the html content is not visible. 
https://user-images.githubusercontent.com/110813321/207893467-9b7263ce-94e6-4775-b929-650f54a00624.MP4

2023-01-10 14:13 UTC, szabinst submitted a review, later dismissed
looks good to me! I had remarks about a few improvement possibilities

2023-01-10 14:13 UTC, szabinst commented on Core/Core/UIViews/CoreWebView.swift
> +extension CoreWebView {
Since this file is already pretty large maybe we could extract it into an extension file.

2023-01-10 14:25 UTC, vargaat requested changes
- [x] Theme switcher is missing on the Teacher app's assignment details.
- [ ] The switch is also missing from the speedgrader (tested with a text submission).
- [x] Discussion reply screen's content size is incorrectly calculated and the message is cut off.

2023-01-13 10:30 UTC, balintbartok approved these changes
QA + 1

2023-01-13 11:50 UTC, szabinst approved these changes
QA+1

2023-01-16 09:02 UTC, balintbartok approved these changes
QA + 1

2023-01-16 10:11 UTC, szabinst approved these changes

2023-01-17 09:31 UTC, merged