CI clean up
instructure/canvas-ios pull request #2365
Opened 2023-02-27 12:04 UTC by szabinst

refs: MBL-16546
affects: Student, Teacher, Parent
release note: Testing
test plan: none

--- edit or delete this section ---
## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="" maxHeight=500></td>
<td><img src="" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product or not needed

2023-02-27 12:24 UTC, inst-danger commented
<details><summary>Parent Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F792f3933-3e50-40d7-945b-8797d648c45a%2Fartifact%2F50a0b9bf8f3d5d50%2Fp%2Fde9e8b6b4b481cf196ff62f029b69f9b&size=150x150" />
</details>


<!-- ParentBuild -->

2023-02-27 12:26 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F1246481e-b5a7-4862-9bf4-18a2ba2534b8%2Fartifact%2Fe47a32b7f81d4ecf%2Fp%2Ff9f717e0a6d3fa277bf864b3a2eca07b&size=150x150" />
</details>


<!-- TeacherBuild -->

2023-02-27 12:35 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F941da400-b4b6-4782-b246-4ef02c754d78%2Fartifact%2F9bad86f2c840350c%2Fp%2F6a8af1da6a68e7edb9df8c1b99fdcb6c&size=150x150" />
</details>


<!-- StudentBuild -->

2023-02-27 12:36 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  One or more files...
  
  4 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.92% | 91.91% | 0.01%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%

[MBL-16546](https://instructure.atlassian.net/browse/MBL-16546)

#### Affected Apps: Student, Teacher, Parent

#### Release Note: 
Testing
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2023-03-01 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/canvas-ios?pullRequest=2365) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/canvas-ios?pullRequest=2365) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/canvas-ios?pullRequest=2365) it.</sub>

2023-03-06 12:40 UTC, vargaat requested changes

2023-03-06 14:58 UTC, szabinst commented on TestsFoundation/TestsFoundation/CoreUIElements/SpringBoard/SpringBoard.swift
> +            splitViewButtonID = "top-affordance:com.instructure.ios.teacher"
fixed!

2023-03-06 14:58 UTC, szabinst commented on TestsFoundation/TestsFoundation/CoreUIElements/SpringBoard/SpringBoard.swift
> +            splitViewButtonID = "top-affordance:com.instructure.icanvas"
fixed!

2023-03-07 13:51 UTC, idevainstr approved these changes

2023-03-07 14:01 UTC, merged