Update edit page dialog presentation options.
instructure/canvas-ios pull request #2377
Opened 2023-03-14 13:48 UTC by vargaat

refs: MBL-16583
affects: Student, Teacher
release note: none

test plan:
- Edit a page in iPad.
- The dialog shouldn't be dismissible with a swipe down gesture nor with a tap outside of the dialog.
- Dialog size should match the New Page dialog's size.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/225021428-3f107217-a5b9-4de5-9ff2-9d968aafe554.PNG" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/225021481-6ebf8f73-69d6-4783-9928-e8d3bab7b536.PNG" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Tested on phone
- [ ] Tested on tablet

2023-03-14 13:59 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Fc8b91c86-60cc-4e39-8dac-ac0d647254ed%2Fartifact%2F719e1fda2688777b%2Fp%2F18ef491e393587234e8ad45e6cd18e0b&size=150x150" />
</details>


<!-- TeacherBuild -->

2023-03-14 14:02 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F7170c0cc-4701-4960-af4e-95520a78adaf%2Fartifact%2F3119490ed5705cfb%2Fp%2F85838f146c4dfe15a11cd3505f46d5b9&size=150x150" />
</details>


<!-- StudentBuild -->

2023-03-14 14:05 UTC, inst-danger commented
<!--
  0 failure: 
  2 warning:  One or more files..., This pull request...
  
  3 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  One or more files are below the minimum test coverage 50%
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  This pull request will not generate a release note.
  </td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.89% | 91.89% | -0%
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift | 48.89% | 48.89% | 0%

[MBL-16583](https://instructure.atlassian.net/browse/MBL-16583)

#### Affected Apps: Student, Teacher
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2023-03-16 09:15 UTC, balintbartok submitted a review, later dismissed
QA + 1

2023-03-16 09:23 UTC, idevainstr requested changes
We should also introduce these changes to the new page dialogue (+) and the other new/edit views for assignments, quizzes, discussions and syllabus to stay consistent.

2023-03-16 12:49 UTC, balintbartok approved these changes
QA + 1

2023-03-16 12:49 UTC, idevainstr approved these changes
QA +1

2023-03-16 12:51 UTC, merged