Dashboard course list API rework
instructure/canvas-ios pull request #2420
Opened 2023-04-13 10:35 UTC by szabinst

This PR contains the following changes: 
- Replaced the existing dashboard course API with the one that we use for All Courses
- Dashboard folder has been rearranged. Instead of segmenting the folder by View, View Model and Model, it's segmented by (Dashboard) Sub-features. Sub-features are arranged in the same View, View Model, Model structure like other folders in the projects. 

## Screenshots

<table>
<tr><th>Dashboard folder - Before</th><th>Dashboard folder - After</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/231732718-bc325d24-d47d-4a8d-9b3b-f05781464a1a.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/231732759-87d43a2c-612b-467d-95a4-53dcad301a82.png" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product or not needed

2023-04-13 10:50 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher

[MBL-16627](https://instructure.atlassian.net/browse/MBL-16627)

<details><summary>:x: XCTest failed: CoreTests/FilePickerViewControllerTests/testDocumentScan</summary>


    XCTAssertNotNil failed
    failed - Presented view controller should not be nil
</details>
<details><summary>:x: XCTest failed: CoreTests/FilePickerViewControllerTests/testImage</summary>


    XCTAssertNotNil failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1b9895ef93c6c6eeb710b673318a1f6e36fc6380
</p>

2023-04-13 13:48 UTC, vargaat requested changes

2023-04-13 13:48 UTC, vargaat commented on Core/Core/Dashboard/K5/View/Homeroom/K5HomeroomMySubjectsView.swift
> +    static let courseCardListViewModel = [
Was this an unintentional rename width Xcode's refactor?

2023-04-13 13:52 UTC, szabinst commented on Core/Core/Dashboard/CourseCardList/Model/Entities/DashboardCard.swift
> +import UIKit
Removed.

2023-04-13 13:54 UTC, szabinst commented on Core/Core/Dashboard/CourseCardList/Model/DashboardCourseCardListInteractorLive.swift
> +    private let courseList: CurrentValueSubject<Course, Never> = .init(.init())
Removed.

2023-04-13 14:19 UTC, szabinst commented on Core/Core/Dashboard/CourseCardList/Model/DashboardCourseCardListInteractorLive.swift
> +                    self.courseListStore.refreshWithFuture(force: true)
I added a reactive extension for exhaust and updated this combineLatest with the appropriate calls.

2023-04-13 14:30 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F0b6a644a-e0d4-49d6-bdca-3a3474ec09d8%2Fartifact%2Fe2babd2ba3740eb1%2Fp%2F505a2e08ae817530cc580b7fb55f0e47&size=150x150" />
</details>


<!-- TeacherBuild -->

2023-04-14 07:33 UTC, vargaat requested changes
Please check `TeacherUITests/TodoUITests/testTodos` the course's name disappeared from the todo cells.

2023-04-14 12:34 UTC, szabinst commented
@vargaat Pushed the fix, CI is green now.

2023-04-17 08:00 UTC, vargaat approved these changes
QA+1

2023-04-18 07:26 UTC, idevainstr approved these changes
QA +1

2023-04-18 07:51 UTC, merged