Course Sync Pages Interactor
instructure/canvas-ios pull request #2443
Opened 2023-05-12 12:35 UTC by szabinst

This PR includes:
- container logic for downloading all kinds of content for a course
- pages download logic

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product or not needed

2023-05-12 15:22 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/Core/Core/CourseSync/CourseSyncDownloader/CourseSyncPagesInteractorPreview.swift:28:1: Vertical Whitespace Violation: Limit vertical whitespace to a single empty line; currently 2 (vertical_whitespace)
    
    
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ecca8b42b35a1b0b646dc0121483c1013e8d2b50
</p>

2023-05-15 14:20 UTC, vargaat requested changes
- [x] `CourseSyncInteractor` has no unit tests.

2023-05-15 14:33 UTC, vargaat commented on Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift
> +                : NSLocalizedString("Select All", comment: "")
As long as the two strings are starting at the same position I'm fine. Is this Xcode's default indentation?

2023-05-15 14:47 UTC, szabinst commented on Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift
> +                : NSLocalizedString("Select All", comment: "")
If the two strings are on a new line, then yes.

2023-05-16 13:00 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F11eb2fba-5c37-45fb-9a75-5c5ab4c0bd69%2Fartifact%2F8f4c34d9c926c4ec%2Fp%2Fc8a437d33e5146a612b388d7300b93b2&size=150x150" />
</details>


<!-- StudentBuild -->

2023-05-16 13:08 UTC, vargaat approved these changes
QA+1

2023-05-16 13:08 UTC, vargaat submitted a review, later dismissed
QA+1

2023-05-16 18:05 UTC, idevainstr approved these changes
QA +1

2023-05-17 07:22 UTC, merged