Fix inst color typos
instructure/canvas-ios pull request #2490
Opened 2023-06-21 13:12 UTC by idevainstr

Login screen buttons should work on master build on iPad.

## Checklist

- [ ] Tested on tablet

2023-06-21 13:29 UTC, inst-danger commented
<!--
  3 failure:  Please add a rele..., Please add which ..., Please add a refe...
  1 warning:  One or more files...
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add which apps this change affects. Example: `affects: Teacher, Student` or `affects: none`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a reference to a jira ticket. For example: `refs: MBL-10023`
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.2% | 92.2% | 0%
Core/Core/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractor.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against afd9291423c590463684b80e703e376ba0655ffd
</p>

2023-06-21 14:05 UTC, vargaat requested changes
Shouldn't we modify the build-colors.js file that generates this color mapping?

2023-06-22 08:47 UTC, vargaat approved these changes

2023-06-22 11:35 UTC, szabinst approved these changes

2023-06-22 11:39 UTC, merged