Offline quizzes
instructure/canvas-ios pull request #2513
Opened 2023-07-14 06:50 UTC by szabinst

refs: MBL-16768
affects: Student
release note: none 
test plan: 
1. Select quizzes when syncing offline content 
2. Turn off internet access
3. Open Quizzes tab
4. You should be able to see the quiz list 
5. On the details page, the `Take quiz`, `Resume quiz`, `View result` button should be disabled. 

## Checklist

- [ ] Tested on phone
- [ ] Tested on tablet

2023-07-14 07:03 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F42c185c5-0402-405d-bea9-0bdb10eff6f5%2Fartifact%2F19c24da00981bbf8%2Fp%2F17b678e5af1c8c99749e5e762051f79a&size=150x150" />
</details>


<!-- StudentBuild -->

2023-07-14 07:06 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16768](https://instructure.atlassian.net/browse/MBL-16768)

<details><summary>:x: XCTest failed: CoreTests/CourseSyncSelectorInteractorLiveTests/testTabList</summary>


    XCTAssertEqual failed: ("4") is not equal to ("3")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 09f8bb9f7695805f4a0e22f29180f1263ca60182
</p>

2023-07-14 14:34 UTC, vargaat reviewed
Code quality looks good. Sync fails for new quizzes. Also the new quiz's "Launch External Tool" button is enabled in offline mode.

2023-07-14 14:34 UTC, vargaat commented on Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncQuizzesInteractor.swift
> +        .map { _ in () }
`CombineExt` provides a nice `.mapToVoid()` function for this.

2023-07-17 11:23 UTC, szabinst commented
Modified the download logic so it filters out new quizzes and LTI button is now also hidden.

2023-07-18 07:42 UTC, szabinst commented
@balintbartok I pushed a fix where this type of quiz is covered.

2023-07-19 10:02 UTC, idevainstr requested changes

2023-07-19 10:02 UTC, idevainstr commented on Student/Student/Quizzes/QuizDetails/QuizDetailsViewController.swift
> +        takeButton.makeUnavailableInOfflineMode()
The takeButton gets funky when this is applied, we might need to change its z order either in code or on the storyboard.
![IMG_5A058E9D8721-1](https://github.com/instructure/canvas-ios/assets/79920680/962d2683-53bc-4a43-aca2-687e33bb1ff7)

2023-07-20 08:40 UTC, balintbartok submitted a review, later dismissed
QA + 1

2023-07-20 10:38 UTC, ndrsszsz approved these changes
QA +1

2023-07-20 11:32 UTC, merged