Login screen accessibility fixes
instructure/canvas-ios pull request #2544
Opened 2023-08-17 09:15 UTC by idevainstr

refs: MBL-16969, MBL-16970
affects: Parent, Student, Teacher
release note: none.
test plan: See ticket.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/5d0a6a0c-a8f6-47e9-8741-a5537d5d04c2" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/d0185f21-6769-4eb0-aee5-c263afc72668" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/969dba3c-c178-4e1d-b64b-212aad5703af" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/9d2113ca-027c-4bde-ade2-7abc0e475666" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2023-08-17 09:28 UTC, vargaat requested changes

2023-08-17 09:28 UTC, vargaat commented on Core/Core/Assets.xcassets/Colors/electric.colorset/Contents.json
These colors are generated from the `build-colors.js` script. I would advice against modifying colors there as they used across the applications and might break the contrast ratio on other places. Until we update the color system I suggest to apply a custom color for this screen's button.

2023-08-17 09:34 UTC, inst-danger commented
<details><summary>Parent Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F522ca614-3061-40e0-b761-01f181a8df7c%2Fartifact%2F81863c957838f7c9%2Fp%2Fa0458a8676b0bec19a62e8f535d7b06f&size=150x150" />
</details>


<!-- ParentBuild -->

2023-08-17 09:36 UTC, inst-danger commented
<!--
  0 failure: 
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-Danger;
-->



#### Release Note: 
none.

#### Affected Apps: Parent, Student, Teacher

[MBL-16969](https://instructure.atlassian.net/browse/MBL-16969)
[MBL-16970](https://instructure.atlassian.net/browse/MBL-16970)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.41% | 92.42% | -0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9ccdd8148b72647229a66d5a6b8b74814200c783
</p>

2023-08-17 09:38 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Fa99dd906-4e9a-4044-add6-9c37b3dce48f%2Fartifact%2F7a360ec4762facf4%2Fp%2F7c53caae6f0b798f69fd3bf0922442fb&size=150x150" />
</details>


<!-- StudentBuild -->

2023-08-17 09:39 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F083a410a-f6bf-4d6e-8822-2d9773e7783e%2Fartifact%2F93330b596bb06688%2Fp%2Fcc04ca06a69ebce8031bdf44047231d6&size=150x150" />
</details>


<!-- TeacherBuild -->

2023-08-18 09:06 UTC, szabinst approved these changes
QA + 1

2023-08-22 07:04 UTC, vargaat approved these changes
QA+1

2023-08-22 07:04 UTC, merged