K5Tests
instructure/canvas-ios pull request #2546
Opened 2023-08-18 11:02 UTC by ndrsszsz

[Bitrise - Canvas iOS - Student - E2ETests](https://app.bitrise.io/build/fac45dca-cdbd-484a-bc9e-59f60793caa1)

4 new K5 test cases (olds are deleted)

2023-08-18 11:16 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Fe6d98bec-bcf2-4686-90cf-041f71414f47%2Fartifact%2F66fb77344c2876c6%2Fp%2Fa124115fbf14cdd45965511214b1f103&size=150x150" />
</details>


<!-- StudentBuild -->

2023-08-18 11:33 UTC, inst-danger commented
<!--
  2 failure:  Please add only o..., Please add only o...
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please add only one release note.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Please add only one affects.</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
None

#### Affected Apps: None

[MBL-16946](https://instructure.atlassian.net/browse/MBL-16946)
[MBL-16771](https://instructure.atlassian.net/browse/MBL-16771)
[MBL-16848](https://instructure.atlassian.net/browse/MBL-16848)
[MBL-16772](https://instructure.atlassian.net/browse/MBL-16772)
[MBL-16808](https://instructure.atlassian.net/browse/MBL-16808)
[MBL-16816](https://instructure.atlassian.net/browse/MBL-16816)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.42% | 92.42% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f7bd6794f88098907c9bd3698bd6d362e20d1bbf
</p>

2023-08-22 07:28 UTC, vargaat requested changes

2023-08-22 07:28 UTC, vargaat commented on TestsFoundation/TestsFoundation/DataSeeding/Course/DSCourse.swift
> +    public let end_at: String?
Why not dates?

2023-08-22 07:28 UTC, vargaat commented on TestsFoundation/TestsFoundation/Extensions/XCUIElementExtensions.swift
> +        case selfSwipeLeft
Maybe adding an associated value to the `swipeLeft` case would be more elegant. This associated value could have a type name `Target` with 2 values: `onApp`, `onElement`, you could make it as an inner enum within the `ElementAction` enum.

2023-08-22 07:28 UTC, vargaat commented on TestsFoundation/TestsFoundation/Helpers/GradesHelper.swift
> +                                  maxPoints: String, letterGrade: String = "") -> XCUIElement {
Not something significant but other parameters are all on a new line, let's follow the patter with this one.

2023-08-22 07:28 UTC, vargaat commented on TestsFoundation/TestsFoundation/Helpers/GradesHelper.swift
> +        let lgSuffix = letterGrade != "" ? " (\(letterGrade))" : letterGrade
Inverting the condition would make it easier to understand.
```suggestion
        let lgSuffix = letterGrade == "" ? "" : " (\(letterGrade))"
```

2023-08-23 07:14 UTC, idevainstr approved these changes

2023-08-23 07:17 UTC, merged