Offline dashboard notification error state
instructure/canvas-ios pull request #2573
Opened 2023-09-08 11:39 UTC by szabinst

refs: MBL-16998
affects: Student
release note: none 
test plan: Start download, turn off Wi-Fi, check notification. 

Notes: 
1. The actual retry logic needs some polish, please focus on the dashboard notification handling for now. 
2. As discussed earlier, the error messages are not yet finalized. 

## Screenshots

https://github.com/instructure/canvas-ios/assets/110813321/5d05da7c-23b3-4323-9fd7-4f8be096a02e

## Checklist

- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode

2023-09-08 11:53 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Fc39e672e-2b3b-4afb-98ee-8f886d73490a%2Fartifact%2F7aa24daed9110663%2Fp%2Fde06d8ec9e0fe353107608f0b2fd5448&size=150x150" />
</details>


<!-- StudentBuild -->

2023-09-08 11:56 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student

[MBL-16998](https://instructure.atlassian.net/browse/MBL-16998)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.45% | 92.45% | 0.01%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a93808bffcc68b8dca1b678420eaa26fc2ecdd5e
</p>

2023-09-11 07:58 UTC, vargaat requested changes
I noticed some strange behavior:

1. Tapping on the failed banner and canceling the sync doesn't make the banner to go away. (It wiggles however on the dashboard like it is about to animate out then coming back.) Tapping it again will show an in-progress sync screen.
2. Restarting the app while the banner is on screen doesn't bring the failed banner back. I would expect to stay it on screen to remind the user that something went wrong during the last sync.
3. Tapping on the banner crashed the app multiple times, although it seems that this is the crash we fixed last week.

Optional improvements:
1. The card animates in/out and the progress updates also animates but there's no fade animation when the card changes from the in progress state to the error state.
2. When using voiceover the card's text is read and it states that it's a button but it's not clear what the button will do. I would make the whole card one a11y element with two actions: "show sync details" and "dismiss". In this case the dismiss button could be hid making the card's handling more straightforward.

2023-09-11 07:58 UTC, vargaat commented on Core/Core/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModel.swift
> +     - offlineModeInteractor: This is used to determine if the feature flag is turned on. If it's off then
This won't produce the expected documentation:
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/a3d7ff19-31ab-4920-8824-8d77d3f04a9b" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/05b6335d-4c45-4b3e-8131-24eb1885fb16" maxHeight=500></td>
</tr>
</table>

2023-09-11 10:02 UTC, szabinst commented
@vargaat Fixed your findings, except the crash. I suspect that my upcoming PR will fix the crash.

2023-09-11 13:02 UTC, vargaat approved these changes
QA+1

2023-09-12 07:10 UTC, merged