Teacher, AssignmentsTests
instructure/canvas-ios pull request #2582
Opened 2023-09-14 11:09 UTC by ndrsszsz

[Bitrise - Canvas iOS - Teacher - E2ETests](https://app.bitrise.io/build/423567a2-939b-490f-aff5-09362cab0ac2)

refs: MBL-17050
affects: Teacher
release note: None
test plan: Tests to pass

2023-09-14 11:19 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F9bcf4a29-cf45-44a0-beb9-0e8ff65ccaae%2Fartifact%2F245d1a6fe2edcd53%2Fp%2Fec0cd9ada41c49afc03fbef4d489412c&size=150x150" />
</details>


<!-- TeacherBuild -->

2023-09-14 11:25 UTC, inst-danger commented
<!--
  0 failure: 
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-Danger;
-->



#### Release Note: 
None

#### Affected Apps: Teacher

[MBL-17050](https://instructure.atlassian.net/browse/MBL-17050)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.46% | 92.46% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 06b642e970a24f706999d27785c95231ec9cd110
</p>

2023-09-15 08:36 UTC, vargaat approved these changes

2023-09-15 15:19 UTC, vargaat requested changes

2023-09-15 15:19 UTC, vargaat commented on rn/Teacher/ios/TeacherE2ETests/CourseDetails/CourseDetailsTests.swift
Is this a merge error?

2023-09-15 15:32 UTC, ndrsszsz commented on rn/Teacher/ios/TeacherE2ETests/CourseDetails/CourseDetailsTests.swift
Kind of.

2023-09-18 09:02 UTC, vargaat approved these changes

2023-09-18 09:56 UTC, merged