Update offline error handling
instructure/canvas-ios pull request #2592
Opened 2023-09-22 11:49 UTC by vargaat

### What changed?
- Generic error dialogs are now hidden in offline mode.
- Fixed a bug in exhaust with future method that caused refresh spinners to never finish.
- Fixed new discussion screen opening in offline mode.
- Updated mastery path selector screen not to work in offline mode.
- Disabled sync button in offline content selector screen.
- Renamed edit dashboard menu item to dashboard settings.

refs: MBL-16599
affects: Student
release note: none

test plan: Play around with the app in offline mode. There should be no error popups nor stuck loading indicators.

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] Tested on phone
- [ ] Tested on tablet

2023-09-22 12:03 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Ff81a020e-d7a9-4db2-a2d0-7159ca215871%2Fartifact%2F7c7b05a6ec0eb2d4%2Fp%2F0f236c41b7e62dd2f48e1cee8d894a66&size=150x150" />
</details>


<!-- StudentBuild -->

2023-09-22 12:35 UTC, szabinst approved these changes
QA + 1

2023-09-26 11:26 UTC, balintbartok approved these changes
QA + 1

2023-09-26 13:17 UTC, balintbartok requested changes
After logging in (to repro: change user to the same user) a generic error pops up.

2023-09-27 14:04 UTC, balintbartok submitted a review, later dismissed
QA + 1

2023-09-28 08:39 UTC, balintbartok approved these changes
QA + 1

2023-09-28 08:42 UTC, ndrsszsz approved these changes
QA +1

2023-09-28 09:13 UTC, merged