Hide unpublished future courses
instructure/canvas-ios pull request #2629
Opened 2023-10-25 10:10 UTC by szabinst

refs: MBL-16986
affects: Student
release note: Fixed an issue where future unpublished courses were shown in All Courses menu
test plan: See ticket

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/d6b3baca-d6a5-472c-8109-5831a7df8aab" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/1e65fb51-2804-4fca-a302-7201cad0a21c" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Tested on phone
- [ ] Tested on tablet

2023-10-25 10:29 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed an issue where future unpublished courses were shown in All Courses menu

#### Affected Apps: Student

[MBL-16986](https://instructure.atlassian.net/browse/MBL-16986)

<details><summary>:x: XCTest failed: CoreTests/CourseListInteractorLiveTests/testFilter</summary>


    XCTAssertEqual failed: ("[]") is not equal to ("["3"]")
</details>
<details><summary>:x: XCTest failed: CoreTests/CourseListInteractorLiveTests/testPopulatesListItems</summary>


    XCTAssertEqual failed: ("[]") is not equal to ("["3"]")
</details>
<details><summary>:x: XCTest failed: CoreTests/CourseListInteractorLiveTests/testRefresh</summary>


    XCTAssertEqual failed: ("[]") is not equal to ("["3"]")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4395ddab548c26049e499c7114b3e748f13729ae
</p>

2023-10-25 10:29 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F9279b142-546a-4d7a-b212-a1eaf03ee506%2Fartifact%2F213da65540fd8cda%2Fp%2Ff220d0bef7ec6115e5eff20384ff000f&size=150x150" />
</details>


<!-- StudentBuild -->

2023-10-25 12:48 UTC, vargaat requested changes
This will affect the course list in the teacher app as well but it should still show up there.

2023-10-27 10:09 UTC, vargaat requested changes

2023-10-27 10:09 UTC, vargaat commented on Core/Core/Courses/CourseList/Model/CourseListInteractorLive.swift
> +
This seems to be unused.

2023-10-31 10:02 UTC, szabinst commented on Core/Core/Courses/CourseList/Model/CourseListInteractorLive.swift
> +
Removed it.

2023-10-31 11:21 UTC, vargaat approved these changes
QA+1

2023-10-31 15:08 UTC, balintbartok approved these changes
QA + 1

2023-10-31 15:08 UTC, merged