Edit groups
instructure/canvas-ios pull request #2635
Opened 2023-11-03 09:44 UTC by szabinst

--- edit or delete this section ---
## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="" maxHeight=500></td>
<td><img src="" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2023-11-03 10:22 UTC, inst-danger commented
<!--
  3 failure:  Please add a rele..., Please add which ..., Please add a refe...
  1 warning:  One or more files...
  
  2 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add which apps this change affects. Example: `affects: Teacher, Student` or `affects: none`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a reference to a jira ticket. For example: `refs: MBL-10023`
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


[MBL-16636](https://instructure.atlassian.net/browse/MBL-16636)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.34% | 92.38% | -0.04%
Core/Core/Groups/GetGroups.swift | 47.73% | 64.62% | -16.89%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against aae2f6226a1f421532e908a55830697539f9c2ed
</p>

2023-11-03 14:17 UTC, szabinst commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F30915d1b-9060-420f-adac-e90e24a78e5b%2Fartifact%2Fd60298f5ad0003c0%2Fp%2F344c399fd3e81a90e76ba55e6fe429dc&size=150x150" />
</details>

2023-11-03 15:41 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F2dae4a5f-9fe3-4a51-a5f4-16cf5d1059ed%2Fartifact%2Fc8a68370f614723b%2Fp%2Fc5037d9a2a8ddeff272bda4d3d1b0c9d&size=150x150" />
</details>


<!-- TeacherBuild -->

2023-11-03 15:44 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F8fd8f86c-ae81-4e7c-bcc3-7aa662b66273%2Fartifact%2Fa7283a551285998b%2Fp%2F54fa59b5b615747f566afa36bed0a667&size=150x150" />
</details>


<!-- StudentBuild -->

2023-11-06 11:02 UTC, vargaat requested changes
Good job on this! I only had a few minor remarks regarding usability:
- **Not in scope.** It looks strange that the future/past.current enrollments section headers are bigger than the Courses and Groups headers. We might revise this.
- **Fixed.** The last course cell looks taller than the others.
- **Fixed.** There's no separator after the group hint text while we have one at the courses section.
- **Fixed.** Account group cell's disclosure indicator is not aligned to the right.
- **Fixed.** Hint texts might need a trailing padding because it looks strange that they stick to the edge of the screen.
- **Fixed.** This was like just as before but then I pop back to the all courses screen the scroll goes to the top forgetting my previous position on the screen. I think this scrolling should only be done on the first load to hide the search bar.
- **Fixed.** Searching for a string that has no match displays the empty state instead of the no results state that also hides the search bar and I'm stuck in this state.

<img src="https://github.com/instructure/canvas-ios/assets/72396990/ad5d2845-ce7b-4e12-ab93-a31dccbfb2b0" width=50% height=50%>
<img src="https://github.com/instructure/canvas-ios/assets/72396990/26d71b4d-9523-4803-815d-8d279848cb56" width=80% height=80%>

2023-11-06 14:46 UTC, szabinst commented on Core/Core/Courses/AllCourses/View/AllCoursesView.swift
> +        .avoidKeyboardArea()
I tested it, seems like it works great without it.

2023-11-07 11:25 UTC, szabinst commented
I added the UI improvements and fixed everything. Please check again @vargaat

2023-11-08 10:08 UTC, vargaat submitted a review, later dismissed
QA+1

2023-11-08 10:23 UTC, balintbartok submitted a review, later dismissed
QA + 1
looks great!

2023-11-08 10:27 UTC, domonkosadam approved these changes
QA + 1

2023-11-08 11:38 UTC, balintbartok approved these changes

2023-11-08 11:48 UTC, domonkosadam approved these changes

2023-11-08 12:07 UTC, merged