Native inbox Course picker
instructure/canvas-ios pull request #2640
Opened 2023-11-08 11:56 UTC by domonkosadam

refs: MBL-14854
affects: All
release note: none

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/546493c5-9548-406c-8d87-57c48dfca67d" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/2f174390-6678-4f91-b049-047c3fc37c5f" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode

2023-11-08 12:02 UTC, inst-danger commented
<details><summary>Parent Build QR Code:</summary>
<img src="" />
</details>


<!-- ParentBuild -->

2023-11-08 12:04 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="" />
</details>


<!-- TeacherBuild -->

2023-11-08 12:04 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="" />
</details>


<!-- StudentBuild -->

2023-11-08 12:38 UTC, inst-danger commented
<!--
  3 failure:  Please add a rele..., Please add which ..., Please add a refe...
  1 warning:  One or more files...
  
  2 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a release note. If no release note is wanted, use `none`. Example: `release note: Fixed a bug that prevented users from enjoying the app.`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add which apps this change affects. Example: `affects: Teacher, Student` or `affects: none`
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a reference to a jira ticket. For example: `refs: MBL-10023`
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


[MBL-14854](https://instructure.atlassian.net/browse/MBL-14854)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.58% | 91.82% | -0.24%
Core/Core/Inbox/ComposeMessage/Model/RecipientContext.swift | 0% | -- | --
Core/Core/Inbox/InboxCoursePicker/ViewModel/InboxCoursePickerViewModel.swift | 0% | -- | --
Core/Core/Inbox/ComposeMessage/Model/ComposeMessageInteractorLive.swift | 0% | 0% | 0%
Core/Core/Inbox/ComposeMessage/ViewModel/ComposeMessageViewModel.swift | 38.17% | 33.97% | 4.2%
Core/Core/Inbox/InboxCoursePicker/Model/InboxCoursePickerInteractorLive.swift | 0% | -- | --
Core/Core/Inbox/Addressbook/ViewModel/AddressbookViewModel.swift | 0% | 0% | 0%
Core/Core/Inbox/Addressbook/Model/AddressbookInteractorLive.swift | 0% | 0% | 0%
Core/Core/Inbox/ComposeMessage/Model/MessageParameters.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 25625e4e7ecc03e8d9820bd3809df9ebdb217115
</p>

2023-11-08 13:10 UTC, vargaat requested changes
Good job in overall!

- I noticed that when selecting a long course name it looks weird that it's center aligned on the compose screen, we could change that to a leading alignment. <img src="https://github.com/instructure/canvas-ios/assets/72396990/3c7a38ac-4354-48f2-b75c-1525c1b7118d" width=50% height=50%>
- A minor UI glitch that when selecting a row the height of the row increases to make space for the checkmark. We could either reduce the checkmark's size or add a minimum height to the row to reserve the space for the checkmark.
- I would change the background color of the view to the one we have for the section headers to avoid the last group cell blending into the background without visual separation. <img src="https://github.com/instructure/canvas-ios/assets/72396990/dd30c13d-4984-494b-9e87-136472fa1352" width=50% height=50%>

2023-11-08 13:10 UTC, vargaat commented on Core/Core/Inbox/InboxCoursePicker/View/InboxCoursePickerView.swift
> +                .background(Color.backgroundLight)
Marking this text as header for voiceover would make the purpose of this text more obvious.

2023-11-08 13:10 UTC, vargaat commented on Core/Core/Inbox/InboxCoursePicker/View/InboxCoursePickerView.swift
> +        }
My comments on the course row apply here as well.

2023-11-08 13:10 UTC, vargaat commented on Core/Core/Inbox/InboxCoursePicker/View/InboxCoursePickerView.swift
> +    private func headerView(_ header: String) -> some View {
Check if SwittUI-s built-in Section works with scrollviews or not. That automatically makes the header view passed to it sticky.

2023-11-14 20:18 UTC, vargaat requested changes
Thank you for the fixes. There are a few items left from my previous review and I noticed these during this review cycle.
- Seems like we lost the left alignment in the context selector screen.<img src="https://github.com/instructure/canvas-ios/assets/72396990/418e1363-3d84-452a-9a35-969f88c29b54" width=50% height=50%>
- Groups don't load recipients and the error page seems a little strange in dark mode.<img src="https://github.com/instructure/canvas-ios/assets/72396990/40a6b8fd-a108-4e04-8b51-5b7b51b9d83e" width=50% height=50%>
- A random improvement idea to turn on auto capitalization for the subject and the message fields for sentences.

2023-11-14 20:18 UTC, vargaat commented on Core/Core/Inbox/InboxCoursePicker/ViewModel/InboxCoursePickerViewModel.swift
> +    private var subscriptions = Set<AnyCancellable>()
Unused.

2023-11-14 20:18 UTC, vargaat commented on Core/Core/Inbox/InboxCoursePicker/View/InboxCoursePickerView.swift
> +                    separator
Indentation seems off. We could extract maybe the header builder to make this part smaller just like you did with the courseRow method.

2023-11-14 20:18 UTC, vargaat commented on Core/Core/Inbox/InboxCoursePicker/View/InboxCoursePickerView.swift
> +                    separator
Indentation is off.

2023-11-16 15:19 UTC, szabinst requested changes
I think we could improve the following three things: 
- When navigating back from the Course picker to the New Message screen, the "New Message" title is misplaced and there's an animation where it moves back to its original place. 
- I think we should include a loading indicator to the Course Picker screen, so we don't have a blank screen while the courses are loading. 

https://github.com/instructure/canvas-ios/assets/110813321/4873e273-9d9c-41bf-825b-0f3f3b0e78f0)

The error screen for no recipients use case, looks a bit unpolished. 

![IMG_0130](https://github.com/instructure/canvas-ios/assets/110813321/07c94891-bbe1-4aa0-8f7c-6213204facc8)

2023-11-20 08:06 UTC, domonkosadam commented
The address book will be fixed in the following ticket.

2023-11-21 08:12 UTC, szabinst approved these changes
QA + 1

2023-11-21 08:50 UTC, vargaat approved these changes

2023-11-21 08:51 UTC, merged