Native Inbox Reply
instructure/canvas-ios pull request #2663
Opened 2023-11-29 12:22 UTC by domonkosadam

refs: MBL-14852
affects: Student, Teacher
release note: none

test plan: Steps are in the ticket

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/ff1b8193-e2b8-4964-9aa8-6eb8297ef3df" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/3fa23aab-2fc8-45e1-ad5d-dfd2d4d8b6d7" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode

2023-11-29 12:30 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  2 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher, Student

[MBL-14852](https://instructure.atlassian.net/browse/MBL-14852)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e01b1ebf252c9ae571670998407626c5f1bbb174
</p>

2023-11-29 12:33 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Ffd1fcb00-42df-450f-a4a2-ed7a92e0619f%2Fartifact%2F41019057b76e6c90%2Fp%2Fa73c5ed78aae7ab1a29d588298810ffd&size=150x150" />
</details>


<!-- TeacherBuild -->

2023-11-29 12:47 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Fbb689cda-a7d0-44b4-91c0-5b56e8923975%2Fartifact%2F232c77cff808e65a%2Fp%2F7723f9a5e8886b27262c83f61332d6f4&size=150x150" />
</details>


<!-- StudentBuild -->

2023-11-29 14:26 UTC, vargaat requested changes
QA+1, I had a few code review findings but otherwise looks good!

2023-11-29 14:26 UTC, vargaat commented on Core/Core/Inbox/ComposeMessage/ViewModel/ComposeMessageViewModel.swift
> +            }
I think we could use `Context(canvasContextID: String)` to make this snippet more simple.

2023-11-29 14:26 UTC, vargaat commented on Core/Core/Inbox/MessageDetails/Model/MessageDetailsInteratorLive.swift
> +            })
I think it would be clearer to setup a new stream for this.

2023-11-30 09:52 UTC, szabinst approved these changes
QA + 1 

The send button changes position when I type more than 2 characters. Let's not forget fixing it in the next PR.

2023-12-01 11:31 UTC, merged