Native inbox addressbook
instructure/canvas-ios pull request #2667
Opened 2023-12-06 14:07 UTC by domonkosadam

# Native iOS address book

refs: MBL-14855
affects: Teacher, Student
release note: none
test plan: Steps are in the ticket

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/4cd030a1-11f9-4cfa-94c7-68bb3d59e11e" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/a43842b0-8506-48de-ab8f-be8132b67a98" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] A11y checked
- [ ] Tested on phone
- [x] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode

2023-12-06 14:18 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F4d7363da-9186-4b5d-9227-41355a411f1f%2Fartifact%2F432edaaa480f92a0%2Fp%2F9e6648d81e290be438f065e5bac8e718&size=150x150" />
</details>


<!-- TeacherBuild -->

2023-12-06 14:21 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F47ac2d94-255a-498b-a15d-e3ae663d0373%2Fartifact%2F6da2eb6ebb279d27%2Fp%2F77c830ca7fcf6d3a4116ce7170d87763&size=150x150" />
</details>


<!-- StudentBuild -->

2023-12-06 14:22 UTC, inst-danger commented
<!--
  3 failure:  Please add only o..., Please add only o..., Build failed, ski...
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please add only one release note.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Please add only one affects.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Teacher, Student

[MBL-14855](https://instructure.atlassian.net/browse/MBL-14855)
[MBL-14852](https://instructure.atlassian.net/browse/MBL-14852)

<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testRoutes</summary>


    Crash: Student (39404) <external symbol>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 67c41b4a05756c180d1629067bfefdce8a465b8c
</p>

2023-12-07 17:01 UTC, vargaat requested changes
Nice work, congrats! I have one remark: I think the address book dialog should have a done or close button on the top right corner all times so when I finished picking recipients I can close the dialog right away. Now I have to pop back to the root and hit cancel which doesn't really cancel anything since my selections stay there. Consult with George regarding this.

2023-12-08 12:07 UTC, szabinst reviewed
Looks good to me but I can echo what Attila suggests.

2023-12-08 12:07 UTC, szabinst commented on Core/Core/Inbox/Addressbook/ViewModel/AddressbookRecipientViewModel.swift
> +    private var canSelectAllRecipient: Bool
These could be changed to `let` instead of `var`.

2023-12-11 10:53 UTC, vargaat requested changes
- Please add/extend tests to have a good test coverage on all the files.
- The done button should be on the top right corner and on all pages. With this version I still have to pop back to the root to close the picker.

2023-12-11 10:53 UTC, vargaat commented on Core/Core/Localizable.xcstrings
> +    "Selected course: (selectedContext!.name)" : {
This seems to be an incorrect localized string.

2023-12-11 10:53 UTC, vargaat commented on Core/Core/Localizable.xcstrings
> +    "Course designers" : {
Let's modify this to "Course Designers".

2023-12-12 08:54 UTC, vargaat approved these changes
QA+1

2023-12-14 14:20 UTC, szabinst approved these changes
QA + 1

2023-12-14 14:49 UTC, merged