XcodeGen for Student project
instructure/canvas-ios pull request #2672
Opened 2023-12-18 11:43 UTC by szabinst

[ignore-commit-lint]

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2023-12-18 13:17 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="" />
</details>


<!-- StudentBuild -->

2023-12-18 13:21 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2f202a30cb25062085e20b23937a624d19a895e1
</p>

2024-01-04 09:37 UTC, vargaat reviewed
I would leave the file reorganization to another PR as it requires more work since we have a lot of places where resource/source file paths are hardcoded. I checked what was in my mind but there could be other places where we have hardcoded paths, all needs to be modified and tested:

- build-colors.js
- build-icons.js
- build-secrets.js
- translations/export.js
- translations/import.js
- coverage/config.json
- setup-parent-secrets.sh
- setup-student-secrets.sh
- setup-teacher-secrets.sh
- Bitrise workflows to be checked (Info.plist locations, adhoc icon stamping, etc.)

2024-01-10 08:53 UTC, vargaat requested changes
Let's finalize the PR and run every CI workflow on this branch to be sure nothing is broken.

2024-01-10 08:53 UTC, vargaat commented on Makefile
> +#	@cd Student; xcodegen
Guess this shouldn't be commented out.

2024-01-10 08:53 UTC, vargaat commented on Student/project.yml
> +      #   product: FirebaseRemoteConfig
What are these for? Let's add some explanation or remove them.

2024-01-10 08:53 UTC, vargaat commented on Student/project.yml
> +      # - package: Firebase
Can we remove this?

2024-01-10 08:53 UTC, vargaat commented on Student/project.yml
> +    #  - target: TestsFoundation/TestsFoundation
Let's remove these if not needed.

2024-01-10 11:45 UTC, szabinst commented on Makefile
> +#	@cd Student; xcodegen
Readded this line.

2024-01-18 17:11 UTC, vargaat requested changes

2024-01-18 17:11 UTC, vargaat commented on Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
Were these version downgrades intentional?

2024-01-19 16:47 UTC, vargaat approved these changes
QA+1, cocoapods mixes up a few things but hopefully not for long

2024-01-19 16:49 UTC, merged