Add dark mode css for discussions
instructure/canvas-ios pull request #2689
Opened 2024-01-11 14:03 UTC by vargaat

### What changed?
- Reverted the changes we made in the color-invert webview feature for discussions and no longer use it.
- Created a separate feature specifically for dark mode discussions that adds CSS overrides to achieve a dark mode like look.
- Not all elements were turned dark, the RCE editor for example remained in light mode including many others.
- The goal was to make everything readable while add as much dark as possible.

refs: MBL-17311
affects: Student, Teacher
release note: none

test plan: Check hybrid discussion in dark mode. Everything should be readable.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/6fc9f80c-7659-4572-8a6e-77735d64f8ff" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/f3c5a2bc-c876-4609-a382-d4df24b75959" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2024-01-11 14:14 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F4577d276-8815-4d44-ad90-99b287121b43%2Fartifact%2Fafdc3426b3fbf097%2Fp%2F4503282c493f4ef2f817c4917b7e58f0&size=150x150" />
</details>


<!-- TeacherBuild -->

2024-01-11 14:18 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher

[MBL-17311](https://instructure.atlassian.net/browse/MBL-17311)

<details><summary>:x: XCTest failed: StudentUnitTests/RoutesTests/testRoutes</summary>


    Crash: Student (39905) <external symbol>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e6cbdf5ed016ce5e913b669e8a48246235fb3c99
</p>

2024-01-12 08:31 UTC, szabinst requested changes
Looks much better than before. Would be great to set a color for the role label. 
See "TEACHER" in the screenshot. 

<img src="https://github.com/instructure/canvas-ios/assets/110813321/e16ec23d-ebca-4ad7-b11d-c3e2ccdac21b" width=300>

2024-01-12 14:50 UTC, vargaat commented
Fixed the teacher and other roles as well.
<img src="https://github.com/instructure/canvas-ios/assets/72396990/af5c9fb6-8897-4ef0-a63c-c893e1bc8769" width=50% height=50%>

2024-01-12 15:44 UTC, szabinst approved these changes
QA + 1

2024-01-15 12:56 UTC, balintbartok approved these changes
QA + 1

2024-01-15 12:56 UTC, merged