Rework ReactiveStore to prevent crashes
instructure/canvas-ios pull request #2696
Opened 2024-01-17 12:55 UTC by szabinst

Rework ReactiveStore to prevent crashes

refs: MBL-17259
affects: Student, Parent, Teacher
release note: Fixed an issue that caused occasional crashes.
test plan: Test the whole app if everything works as before.

## Checklist

- [ ] Tested on phone
- [ ] Tested on tablet

2024-01-17 12:56 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="" />
</details>


<!-- StudentBuild -->

2024-01-17 13:04 UTC, inst-danger commented
<details><summary>Parent Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Fa917d068-09c6-4ee1-8876-47709bd007d4%2Fartifact%2Fec8e15e07c86b99c%2Fp%2F41fbb656ea4b9de5aa0c9b2758e16524&size=150x150" />
</details>


<!-- ParentBuild -->

2024-01-17 13:05 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F7f3ce25c-aac0-4d93-bd4b-eabae354e823%2Fartifact%2Fdc409cbe94bc0eda%2Fp%2Fae846b37575fd9869c13bb7c2adb3dff&size=150x150" />
</details>


<!-- TeacherBuild -->

2024-01-17 13:10 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Fixed an issue that caused occasional crashes.

#### Affected Apps: Student, Parent, Teacher

[MBL-17259](https://instructure.atlassian.net/browse/MBL-17259)

<details><summary>:x: XCTest failed: CoreTests/CourseSyncAnnouncementsInteractorLiveTests/testFailuresReported</summary>


    failed - Received unexpected output from publisher.
    failed - Unexpected finish event while waiting on failure.
    failed - Received unexpected output from publisher.
    failed - Unexpected finish event while waiting on failure.
    failed - Received unexpected output from publisher.
    failed - Unexpected finish event while waiting on failure.
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8cdb5b8338322587e31191bdccc9d1e614a2c998
</p>

2024-01-18 10:42 UTC, vargaat requested changes
Good job on making the store stateless, this is much safer to use now. I had some comments on the parameter naming and the function doc wording, let me know your thoughts.

2024-01-18 11:10 UTC, szabinst commented on Core/Core/Store/ReactiveStore.swift
> +        publishDatabaseChanges: Bool = false
I actually named this property exactly `keepObservingDatabaseChanges` at first, but changed it later on. I'll change it back.

2024-01-18 12:56 UTC, szabinst commented on Core/Core/Store/ReactiveStore.swift
> +    ///     - forceFetch: Tells the fetch request if it should get data from the API or from cache. Defaults to **false**.
Updated the parameter name.

2024-01-18 12:56 UTC, szabinst commented on Core/Core/Store/ReactiveStore.swift
> +    /// emitted by the publisher.
Reworded the description.

2024-01-19 08:54 UTC, vargaat approved these changes
QA+1

2024-01-19 16:51 UTC, merged