Disable Discussions tab in offline mode if discussionRedesign is enabled
instructure/canvas-ios pull request #2711
Opened 2024-01-31 15:12 UTC by szabinst

Disable Discussions tab in offline mode if discussionRedesign is enabled.

affects: Student

[ignore-commit-lint]

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] Tested on phone
- [ ] Tested on tablet

2024-01-31 15:23 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Ff31b6b54-1a7c-4030-a132-5bca9776b1f0%2Fartifact%2F62ff18e3bd9a854d%2Fp%2Fe7756888d2519d103bde5a305a2868fe&size=150x150" />
</details>


<!-- StudentBuild -->

2024-01-31 15:28 UTC, inst-danger commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 92.04% | 92.06% | -0.02%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f82539f0a6481e4e226e7cc92dea829ac759824a
</p>

2024-01-31 16:18 UTC, vargaat submitted a review, later dismissed
QA+1, Discussions row got disabled in offline mode when the redesign flag was enabled. It stayed enabled when the flag was disabled.

2024-01-31 19:15 UTC, balintbartok requested changes
the same logic should be applied to announcements as well

2024-02-01 08:03 UTC, vargaat approved these changes
QA+1, Announcements got disabled too

2024-02-01 12:47 UTC, balintbartok approved these changes
QA + 1

2024-02-01 12:47 UTC, merged