Student - New E2E tests for Assignments
instructure/canvas-ios pull request #2712
Opened 2024-02-05 12:15 UTC by ndrsszsz

### New E2E tests for Assignments

- testLockedAssignment
- testFutureAssignment
- testExcusedStatus
- testAttemptSelectorAndSubmissionAndRubricScreen

2024-02-05 12:26 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F68fb0136-269a-4fc6-8574-a35404f84a00%2Fartifact%2Faff1046d390bcec1%2Fp%2Feb5655960d5b73193c8a809237b07433&size=150x150" />
</details>


<!-- StudentBuild -->

2024-02-05 12:31 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
None

#### Affected Apps: None

[MBL-17335](https://instructure.atlassian.net/browse/MBL-17335)

<details><summary>:x: Swift lint</summary>


    ❌ /Users/vagrant/git/TestsFoundation/TestsFoundation/DataSeeding/Rubric/CreateDSRubricRequest.swift:39:30: Colon Spacing Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals (colon)
    /Users/vagrant/git/TestsFoundation/TestsFoundation/DataSeeding/Rubric/CreateDSRubricRequest.swift:41:97: error: Colon Spacing Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals (colon)
    /Users/vagrant/git/TestsFoundation/TestsFoundation/DataSeeding/Rubric/CreateDSRubricRequest.swift:71:29: error: Colon Spacing Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals (colon)
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7fdbc0af55f7c63dd3d7cb6b52d84e9eb6f15187
</p>

2024-02-08 10:38 UTC, szabinst approved these changes

2024-02-08 16:01 UTC, vargaat requested changes
Nice work, this is an important area in the app. As I see, we don't test the rubric's description popup, let's add some assertions for that as well

2024-02-09 17:35 UTC, ndrsszsz commented on Student/StudentE2ETests/Assignments/AssignmentsTests.swift
> +    }
Done! 🙂

2024-02-13 12:12 UTC, szabinst approved these changes

2024-02-13 12:32 UTC, vargaat approved these changes

2024-02-13 12:33 UTC, merged