What-if UI elements
instructure/canvas-ios pull request #2740
Opened 2024-03-05 16:34 UTC by szabinst

WhatIf UI

refs: MBL-17303
affects: Student, Parent
release note: none
test plan: Check figma

## Notes
- Using `List` now to access `swipeActions` 
- Because of this you'll see that there's a space before section headers so I decided to use a clear background for the custom view and let the OS color the header. Otherwise there would be a weird transition with colors when the stretched out header scales down in size when scrolling. 

## Screenshots

<table>
<tr><th>Toggle</th><th>Editor</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/6851401c-d47d-4d83-862c-a596ea70c5b5" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/d25ea337-3c27-43af-9657-d0fb387f32be" maxHeight=500></td>
</tr>
<tr><th>Revert</th><th>Swipe action</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/625cda0a-5985-4aa3-99f5-7a5814eb0ba3" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/98f36357-da5d-4f0a-adaa-8dabfabb76fe" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2024-03-05 16:41 UTC, szabinst commented on Core/Core/Grades/View/GradeListView.swift
> +//        .buttonStyle(ContextButton(contextColor: courseColor))
buttonStyle doesn't play nicely with list row. If buttonStyle is added, additional buttons can't be pressed.

2024-03-05 16:43 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  2 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Parent

[MBL-17303](https://instructure.atlassian.net/browse/MBL-17303)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ceee4a3ee38bc04e799d5cf294c67e44149bae8b
</p>

2024-03-05 16:44 UTC, inst-danger commented
<details><summary>Parent Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F0e8ad2b3-354c-4fc7-8dab-55b429585827%2Fartifact%2Fd85af80a1d299515%2Fp%2Fe9c883413702db8fac732aa3b2c3a128&size=150x150" />
</details>


<!-- ParentBuild -->

2024-03-05 16:57 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F8d9d7b82-76ad-4faa-8b3d-e7c01c17e417%2Fartifact%2F140fcc949434886d%2Fp%2F935241aaa482e95dfb971043e658527f&size=150x150" />
</details>


<!-- StudentBuild -->

2024-03-06 11:21 UTC, vargaat requested changes
I tested on an iPad with iOS 16.7.1, here are my findings:

1. The what-if text box is too small. I entered 123 but only 2 digits are displayed.
2. The baseline of the text fields and their labels are not aligned vertically.
![IMG_0314](https://github.com/instructure/canvas-ios/assets/72396990/e8ba77e5-be99-4081-84de-ec68b7bc9961)
3. The edit grade icon is always displayed, even when I have the what-if score disabled.
![IMG_0313](https://github.com/instructure/canvas-ios/assets/72396990/00d2ddb5-9fef-4f3a-aaad-d6eb119e53fe)
4. The dialog doesn't seem to respect dynamic text size settings.
![IMG_0315](https://github.com/instructure/canvas-ios/assets/72396990/5b38a3be-b03b-47af-a326-3a7d4e6f1dcc)

2024-03-07 17:00 UTC, ndrsszsz commented
If I turn the phone to landscape then the list with the assignments and grades disappear like this:

![IMG_0003](https://github.com/instructure/canvas-ios/assets/128469459/0ccf4a10-6e4e-4414-b241-dc5ae53799c9)

2024-03-18 14:02 UTC, szabinst commented
@ndrsszsz I fixed it, please check again.

2024-03-18 16:01 UTC, ndrsszsz approved these changes
QA +1

2024-03-19 13:45 UTC, vargaat approved these changes
QA+1

2024-03-19 13:48 UTC, vargaat commented
The swipe to revert gesture should be disabled if the what if score toggle is off in the next PR.

2024-03-19 14:37 UTC, szabinst commented
@vargaat Good catch. Will do that.

2024-03-19 14:37 UTC, merged