Hide student names in anonymous ungraded surveys
instructure/canvas-ios pull request #2764
Opened 2024-04-09 07:52 UTC by szabinst

refs: MBL-17458
affects: Teacher
release note: Anonymous ungraded surveys now hide student names. Anonymous submissions show a numbered list of students instead of showing student multiple times. 
test plan: See ticket and test other anonymized submission formats. 

### What's new
- Anonymous ungraded surveys now hide Student names and avatars and use a numbered anynomized list. (Student 1, Student 2, etc..)
- Other anonymous submissions are displayed with the same logic as above instead of simply showing (Student, Student) 

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/f569cbbe-5b1d-4902-830b-8f6e6c77e275" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/91e59df8-7ded-478b-a2b0-0a6eb2d60e07" maxHeight=500></td>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/c751f920-b577-4f95-b7e5-f872f535e383" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/e61ba120-d6ef-4bd5-928a-e0ac5cd1b3d9" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2024-04-09 08:03 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F1919633a-adc0-44b0-94bc-f0d3e8a68aca%2Fartifact%2F367d3df952b7e384%2Fp%2F08c04510b696ffa51ff85f98455db1fc&size=150x150" />
</details>


<!-- StudentBuild -->

2024-04-09 08:03 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2Febe4a7c4-fc0b-47ce-a9d9-4976d0291649%2Fartifact%2Fb60e26d88901c86e%2Fp%2F873e59e3f12d7bb893689af165a22905&size=150x150" />
</details>


<!-- TeacherBuild -->

2024-04-09 08:09 UTC, inst-danger commented
<!--
  0 failure: 
  0 warning: 
  
  4 markdown notices
  DangerID: danger-id-Danger;
-->



#### Release Note: 
Anonymous ungraded surveys now hide student names. Anonymous submissions show a numbered list of students instead of showing student multiple times.

#### Affected Apps: Teacher

[MBL-17458](https://instructure.atlassian.net/browse/MBL-17458)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.87% | 91.86% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bbb5b9a2a8970cfdcead04041668d3a2a2c76340
</p>

2024-04-09 14:09 UTC, vargaat requested changes
The user name initials still can be seen as the profile image and that can be used to deduct the actual user (Cordelia Webb in this case). 

![Screenshot 2024-04-09 at 16 06 20](https://github.com/instructure/canvas-ios/assets/72396990/e8887135-efa5-4f18-adae-78f3a20a2de8)

2024-04-09 14:49 UTC, rh12 commented on rn/Teacher/ios/Teacher/Submissions/QuizSubmissionList/Model/Entities/QuizSubmissionListItem.swift
> +                displayName = String(localized: "Student \(index + 1)", bundle: .core)
AFAIK there is no need for `bundle: .core` anymore

2024-04-09 14:49 UTC, rh12 commented on rn/Teacher/ios/Teacher/Submissions/SubmissionListViewController.swift
> +                nameLabel.text = String(localized: "Student \(row)", comment: "")
We could also drop the empty comments

2024-04-10 11:44 UTC, rh12 approved these changes
QA + 1

2024-04-10 12:00 UTC, szabinst commented on Core/Core/SwiftUIViews/Avatar.swift
> +                .background(Color.backgroundLightest)
I have no knowledge on that, first time seeing this class tbh.

2024-04-11 10:01 UTC, ndrsszsz approved these changes
QA +1

2024-04-11 11:19 UTC, vargaat approved these changes
QA+1

2024-04-11 11:19 UTC, merged