Skip offline sync without courses
instructure/canvas-ios pull request #2802
Opened 2024-05-30 10:35 UTC by szabinst

Skip offline sync without selected courses.

refs: MBL-17204
affects: Student
release note: Offline sync skips cases when there are no courses selected
test plan: Build from Xcode to easily trigger a sync, check if sync only occurs when there are offline selected courses.

## Checklist

- [x] Tested on phone
- [ ] Tested on tablet

2024-05-30 10:46 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F8e41952d-26c0-4afc-88d1-cd119f69dc1c%2Fartifact%2Fec42704a85cbd5c3%2Fp%2F4ad6a9a278bf5d86c4dd304cd23f0cb4&size=150x150" />
</details>


<!-- StudentBuild -->

2024-05-31 09:43 UTC, vargaat requested changes
I accidentally was able to reproduce the "0 courses have been synced notification." the following way:
- I had a course that was selected for offline sync in the past.
- This course had course participation setup with and end date and the "Restrict students from viewing course after course end date" option was turned on.
- The end date has passed and the course disappeared both from the dashboard and from the all courses screen.
- The auto sync still started since there was a course selected to be synced.
- I received the 0 courses synced notification.

I'm not sure yet that at which point should we clear this course or if this can be avoided at all if the user doesn't open the offline sync selector screen after a course has disappeared.

<img src="https://github.com/instructure/canvas-ios/assets/72396990/b8eebe71-ad5e-4179-a9cb-8da6d95a0f84" width=50% height=50%>

2024-05-31 12:44 UTC, szabinst commented
@vargaat That's a really nice catch, I'll think about it.

2024-06-05 09:41 UTC, rh12 approved these changes
QA + 1

2024-06-10 12:10 UTC, vargaat approved these changes

2024-06-10 13:44 UTC, merged