Offline sync selector updates
instructure/canvas-ios pull request #2807
Opened 2024-06-04 11:41 UTC by szabinst

Offline selector updates

refs: MBL-17104
affects: Student
release note: none
test plan: See ticket

## Screenshots

<table>
<tr><th>Dialog</th>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/49112bbb-5cdb-4a1a-9622-27b22fd7dd67" height=500></td>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Approve from product

2024-06-04 11:52 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Fbuild%2F4b572f3e-4e59-45c3-91ac-b5e7bc54e706%2Fartifact%2F9ee076575b463c1d%2Fp%2F61ac8b997fcc81ce94547dee65492a01&size=150x150" />
</details>


<!-- StudentBuild -->

2024-06-04 13:30 UTC, vargaat requested changes
QA+1, I added some minor review findings.

2024-06-04 13:30 UTC, vargaat commented on Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift
> +        message: "Selection changes that you may had made won't be saved. Are you sure you want to cancel?",
Let's localize this line.

2024-06-04 13:30 UTC, vargaat commented on Core/Core/SwiftUIViews/ConfirmationAlert.swift
Guess the changes in this file were accidental.

2024-06-05 09:14 UTC, rh12 commented on Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift
> +            localized: "Selection changes that you may had made won't be saved. Are you sure you want to cancel?",
This one is not added to xcstrings

2024-06-05 09:19 UTC, szabinst commented on Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift
> +            localized: "Selection changes that you may had made won't be saved. Are you sure you want to cancel?",
Pushed the missing change.

2024-06-05 09:54 UTC, rh12 commented
When everything is deselected and "Sync" is tapped we show the regular confirmation dialog, which states:
```
Sync Offline Content?
This will sync ~Zero KB content. It may result in additional charges from your data provider if you are not connected to a Wi-Fi network.
[ Cancel | Sync ]
```
As an improvement this could display something more relevant, like
```
Clear Offline Content?
No content was selected. This will clear any previously synced content from your device.
[ Cancel | Clear ]
```
(A related thought to change the blue "Sync" button to "Clear local content" on the sync screen)

This is just and idea and may be out of scope in this PR.

2024-06-05 09:58 UTC, rh12 approved these changes
QA + 1
Minor thought: would it make sense to only show the cancel confirmation dialog if there are actually any changes in the selection?
If so, the confirmation message could be simplified a bit, as well.

2024-06-05 12:05 UTC, szabinst commented
@rh12 I thought about it but that would increase the scope for this rather simple modification.

2024-06-11 08:59 UTC, vargaat approved these changes

2024-06-11 08:59 UTC, merged