Enable copy and select text in inbox messages
instructure/canvas-ios pull request #2913
Opened 2024-10-02 13:08 UTC by Ahmed-Naguib93

[refs:MBL-17850](https://instructure.atlassian.net/browse/MBL-17850)
affects: Student, Teacher
release note: Enabled copy and select text in inbox messages

## Test plan:
- Opne inbox messages.
- Select any message.
- Try to select or copy any text.
## Screenshots

https://github.com/user-attachments/assets/79eba56f-5f11-44f3-adc0-a7cb8a19d76a

## Checklist
- [ ] Tested on phone
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-10-02 13:15 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2Fa8b2e95204a04524%2Fpublic-install-page%2Fad6b4128493c6f0e6ab2111b0d5e3612&size=150x150" />
</details>


<!-- TeacherBuild -->

2024-10-02 13:15 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2Fe9d1fe1a4fa5a9c3%2Fpublic-install-page%2Fd11d9038c659b7710a568ec8d1d7b064&size=150x150" />
</details>


<!-- StudentBuild -->

2024-10-02 13:20 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  One or more files...
  
  4 markdown notices
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Enabled copy and select text in inbox messages

#### Affected Apps: Student, Teacher

[MBL-17850](https://instructure.atlassian.net/browse/MBL-17850)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.46% | 91.45% | 0.01%
Core/Core/Planner/CalendarEvent/Model/API/PostCalendarEventRequest.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/View/CustomFrequencyComponents/OccurrencesCountInputDialog.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/Model/Helpers/RecurrenceRule+SelectionDescription.swift | 43.33% | 43.33% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 988bd9e8e574b93fa451a64c20c1790c20275346
</p>

2024-10-03 12:27 UTC, rh12 requested changes
It works as expected.

Some points of improvement:
1. Dragging the selection does not scroll the view, so user needs to scroll and adjust selection repeatedly. (Minor issue, may not worth the effort)
2. It would be good to have the "Select All" button to be shown besides the "Copy", etc. Because of the scrolling/reselecting limitation above, without this it's rather annoying to try to select all text (which was the way it worked before)

2024-10-03 12:27 UTC, rh12 commented on Core/Core/SwiftUIViews/SelectableTextViewWrapper.swift
> +        case attributedText(value: AttributedString)
```suggestion
        case text(String)
        case attributedText(AttributedString)
```

2024-10-03 12:27 UTC, rh12 commented on Core/Core/SwiftUIViews/SelectableTextViewWrapper.swift
> +        textType: TextType,
IMHO this init could be replaced with one expecting a `text: String` and another expecting `attributedText: AttributedString`. Those could setup the `textType` property, and `TextType` could be private.
But if you rather prefer it this way that's also ok.

2024-10-03 15:10 UTC, vargaat approved these changes
QA+1

2024-10-03 15:11 UTC, merged