Move the cursor to the end when pasting long text
instructure/canvas-ios pull request #2927
Opened 2024-10-11 11:00 UTC by Ahmed-Naguib93

refs: [MBL-17838](https://instructure.atlassian.net/browse/MBL-17838)
affects: Student , Teacher
release note: Moved the cursor to the end when pasting long text

## Test Plane
1- Open new message.
2- Set long text.
3- will see the view scroll down and move the cursor to the end.

## Screenshots

https://github.com/user-attachments/assets/5b18cbbc-c84d-4432-acb5-8f65e957de96

## Checklist
- [ ] Tested on phone
- [ ] Tested in light mode

2024-10-11 11:07 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2Fb9bc879835ec06dd%2Fpublic-install-page%2F5b2cc87fc71ae73f3b3cb54d46aee29a&size=150x150" />
</details>


<!-- TeacherBuild -->

2024-10-11 11:12 UTC, inst-danger commented
<!--
  0 failure: 
  1 warning:  One or more files...
  
  4 markdown notices
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  </tbody>
</table>


#### Release Note: 
Moved the cursor to the end when pasting long text

#### Affected Apps: Student, Teacher

[MBL-17838](https://instructure.atlassian.net/browse/MBL-17838)

Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 91.12% | 91.12% | 0.01%
Core/Core/Planner/CalendarEvent/Model/API/PostCalendarEventRequest.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/View/CustomFrequencyComponents/OccurrencesCountInputDialog.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarEvent/Model/Helpers/RecurrenceRule+SelectionDescription.swift | 43.33% | 43.33% | 0%
Core/Core/Grades/View/CustomSwipeAction.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f5432f2f7cbb9838131043b385ebd9fbab089d79
</p>

2024-10-15 13:03 UTC, vargaat requested changes
I get this strange behavior on iOS 17.5.1. Besides that, I think we can't just scroll to the end of the text (where attachments are) because the user is not necessarily pasting text at the end of the message. The original bug was about when you enter some characters after pasting a long text the characters are not entered to where the cursor is visible but instead at the end of the document. If we could fix that alone would be enough, if we could scroll to the end of the **pasted** text that would nice to have.

https://github.com/user-attachments/assets/9e1fcf39-6b6b-4d43-b5fb-d6171ea8a3c8

2024-10-15 16:35 UTC, Ahmed-Naguib93 commented
> Moved the cursor to the end when pasting long text

Thanks, i fixed the issues please check again 

https://github.com/user-attachments/assets/28aa7053-8ad2-462b-b280-27cb0c95b1ab

2024-10-15 17:54 UTC, Ahmed-Naguib93 commented on Core/Core/Inbox/ComposeMessage/View/UITextViewWrapper.swift
> -    @Binding var text: String
I removed this file, because no longer used

2024-10-17 11:14 UTC, Ahmed-Naguib93 commented
> `InstUI.TextEditorCell` on iOS 17.

Yes, I have tested it on iOS 18.0.1, and it is working fine. This is a standard UITextView, an older controller.

2024-10-17 11:26 UTC, rh12 commented
> Yes, I have tested it on iOS 18.0.1, and it is working fine. This is a standard UITextView, an older controller.

Sorry, I tested the right thing, but wrote about the other thing... anyway, please disregard the PR comment above about the doc comment in code.

Approving

2024-10-17 11:27 UTC, rh12 approved these changes

2024-10-21 09:25 UTC, szabinst approved these changes
QA + 1

2024-10-21 09:41 UTC, suhaibabsi-inst approved these changes
QA + 1

2024-10-21 09:46 UTC, vargaat approved these changes

2024-10-21 09:53 UTC, merged