[Horizon] Inbox
instructure/canvas-ios pull request #2947
Opened 2024-10-22 15:03 UTC by Ahmed-Naguib93

Add Inbox feature like student app.

2024-10-22 15:07 UTC, inst-danger commented
<!--
  2 failure:  You have included..., Build failed, ski...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>You have included an invalid app. Valid values are: Student, Teacher, Parent, None</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Added inbox
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 45503255b01ce6660fa6a5a1546591e7027a2eb6
</p>

2024-10-24 09:43 UTC, szabinst requested changes
Please add `// TODO: xyz` to all the color changes so we don't forget to change it back once we have high fidelity designs.

2024-10-24 09:44 UTC, szabinst commented on Horizon/Horizon/Sources/Features/HorizonTabBarController.swift
> +        inboxSplit.tabBarItem.makeUnavailableInOfflineMode()
Please comment out this for now as we don't have exact plans for offline support.

2024-10-24 09:46 UTC, szabinst commented on Horizon/Horizon/Sources/Routing/HorizonRouter.swift
> +private func offlineFileDetails(
We don't need this for now.

2024-10-24 09:46 UTC, szabinst commented on Horizon/Horizon/Sources/Routing/HorizonRouter.swift
> +        RouteHandler("/courses/:courseID/files/:section/:resourceID/:fileID/offline", factory: offlineFileDetails),
We don't need this for now.

2024-10-24 16:29 UTC, inst-danger commented
<details><summary>Horizon Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2F0c102b2d79cf7462%2Fpublic-install-page%2F3872f47abad084428ba6bdb38943f9e1&size=150x150" />
</details>


<!-- HorizonBuild -->

2024-10-25 09:50 UTC, szabinst approved these changes
QA + 1

2024-10-25 09:50 UTC, merged