Assignment List Preferences (Filter, GroupBy, Grading Period)
instructure/canvas-ios pull request #2948
Opened 2024-10-22 15:36 UTC by ndrsszsz

refs: MBL-17932
affects: Student, Teacher
release note: Added functionality to filter and group assignments.
test plan: See ticket

#### Assignment List screen

- Add Filter icon in Navigation Bar (should turn to solid if there's an active filtering and that differs from the default settings).
- Upgrade sections to be collapsable.

#### Assignment Filter screen

- Grading Period section: Should only be visible if there are multiple Grading Periods (default option is All Grading Periods).
- Group By section: Should always be visible (default option is Due Date).

## [Figma](https://www.figma.com/design/d0XYwwGe37hEWdmArVVBhr/%E2%8F%B3-%5BWIP%5D-Mobile-Desig-Sprint-%5BQ2-Q3%5D?node-id=2743-304395&t=RMMZJtV49pYLbDSh-1)

## Test Plan

See ticket.

### Assignment Filter screen
- Navigation bar title should contain the name of the course under the screen title.
- Done button should always be visible and active.
- Grading Period section of the screen should only be visible if there are multiple grading periods.
- Default setting for grading periods is "All Grading Periods" right now. (Will be modified to the currently active grading period)
- Sort By section should always be visible and should have "Due Date" option selected by default.
- Changes are saved to userdefaults (except grading period settings).

## Screenshots

### Assignment List
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/fab5bf88-fe7d-4ec2-a413-4cc1b5454f9e" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/57226d87-6775-4332-8dba-cfe9e4744575" maxHeight=500></td>
</tr>
</table>

### Assignment Filter
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/ae42a650-538b-4c37-9d75-308e76197def" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/e6216cf9-6522-4872-b412-ea0089b54044" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2024-10-22 15:36 UTC, ndrsszsz commented
Unit tests will be added later.

2024-10-22 15:40 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  3 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



#### Release Note: 
Added Filter options to Assignment List

#### Affected Apps: Student, Teacher

[MBL-17932](https://instructure.atlassian.net/browse/MBL-17932)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c2e2955b1c7e1ccc9e49a3f4b8ac56894bf0bac9
</p>

2024-10-28 09:46 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2F742b5c0ab42c0001%2Fpublic-install-page%2Fe2daeb18eb5f0e373dbd19d14eb85205&size=150x150" />
</details>


<!-- TeacherBuild -->

2024-10-28 09:47 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2F8847c336bd1d4a8b%2Fpublic-install-page%2F44de4850d3033faf6b3753d6f02fd9ff&size=150x150" />
</details>


<!-- StudentBuild -->

2024-10-29 07:04 UTC, rh12 reviewed
Great to see this coming together again after the design changes!

I've got a couple of small comments

2024-10-29 14:43 UTC, ndrsszsz commented on Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListPreferencesViewModel.swift
> +    let courseId: String
We don't even need it here. 🙂

2024-10-31 00:28 UTC, rh12 submitted a review, later dismissed
QA + 1

My only issue is that when the filter screen is dismissed via swipe down gesture, IMHO it should apply the changes to the list screen, just like when tapping "Done".
IIRC this is what we discussed on the meeting as well. Please clarify this with someone on product side.

2024-10-31 14:45 UTC, ndrsszsz commented
> QA + 1
> 
> My only issue is that when the filter screen is dismissed via swipe down gesture, IMHO it should apply the changes to the list screen, just like when tapping "Done". IIRC this is what we discussed on the meeting as well. Please clarify this with someone on product side.

Agreed. I updated it to also save the changes when the screen is dismissed.

2024-10-31 15:47 UTC, suhaibabsi-inst reviewed
Thanks @ndrsszsz !
Generally speaking, looks good to me. Just few minor comments to consider, but they are not blocking of their nature. There few area that deserves a bit of cleanup in my opinion, especially those with multi conditional statements, but those could be kept for later I think.

Code +1

2024-10-31 15:47 UTC, suhaibabsi-inst commented on Core/Core/Assignments/AssignmentList/View/AssignmentGroupView.swift
> +    private func headerView() -> some View {
I think you don't this method to be tagged with `@ViewBuilder` since it only returns single view.

2024-10-31 15:47 UTC, suhaibabsi-inst commented on Core/Core/Assignments/AssignmentList/View/AssignmentListScreen.swift
> +                    Text("Grading Period:")
You need pass `.core` to bundle here and in all instances of `Text`

```swift
 Text("Grading Period:", bundle: .core)
```

2024-10-31 15:47 UTC, suhaibabsi-inst commented on Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListPreferencesViewModel.swift
> +        subtitle: "Late, Submitted",
Localization ?

2024-10-31 15:47 UTC, suhaibabsi-inst commented on Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListViewModel.swift
> +        return env.subscribe(LocalUseCase(scope: scope)) { }
Is it necessary here to pass a trailing closure here ? Can't we remove it?

2024-10-31 15:47 UTC, suhaibabsi-inst commented on Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListViewModel.swift
> +        if gradingPeriod == selectedGradingPeriod && sortingOption == selectedSortingOption && filterOptions == selectedFilterOptions {
**Not blocking:**
Let's spread those into multilines

2024-10-31 16:51 UTC, suhaibabsi-inst commented
QA + 1

2024-10-31 16:56 UTC, suhaibabsi-inst approved these changes
Code +1 
QA + 1

Please address above comments at your convenience.

2024-10-31 17:45 UTC, ndrsszsz commented on Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListPreferencesViewModel.swift
> +        subtitle: "Late, Submitted",
Nice catch, forgot about it. Thanks.

2024-11-03 09:55 UTC, suhaibabsi-inst submitted a review, later dismissed
Thanks @ndrsszsz !

2024-11-04 12:35 UTC, rh12 approved these changes
QA + 1 again

2024-11-06 09:13 UTC, vargaat requested changes
I compared my assignment list from the app to web and our list misses a few assignments even when all filter options are turned on: 1 from "Middle Group" and 2 from "Test Assignment Group". I haven't checked "Test Assignment Group" since there are too many assignments there.

<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/9aa59dad-c3b0-49e9-b77d-88f6becd2fbc" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/ffbf8d7d-b4c9-446f-8561-b5f831f50d87" maxHeight=500></td>
</tr>
</table>

2024-11-06 13:00 UTC, vargaat submitted a review, later dismissed
The issue I discovered is not related to this PR.

QA+1

2024-11-06 14:20 UTC, rh12 approved these changes
QA + 1 again

Found some minor VoiceOver issues around ChecboxCell subtitles and the Filter button, but these can wait for the next PR. Discussed details offline.

2024-11-06 14:21 UTC, vargaat approved these changes

2024-11-06 14:28 UTC, merged