[Horizon] Assignment details text entry submission
instructure/canvas-ios pull request #2959
Opened 2024-11-01 13:54 UTC by Ahmed-Naguib93

Assignment details text entry submission

2024-11-01 14:02 UTC, inst-danger commented
<details><summary>Horizon Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2F1308316d94cb5036%2Fpublic-install-page%2F6189d7f6a04895f6d551eb2451aa99f6&size=150x150" />
</details>


<!-- HorizonBuild -->

2024-11-01 14:08 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/CourseSyncSyllabusInteractorLiveTests/testSuccessfulFetch</summary>


    XCTAssertEqual failed: ("0") is not equal to ("2")
    XCTAssertEqual failed: ("nil") is not equal to ("Optional("1")")
    XCTAssertEqual failed: ("nil") is not equal to ("Optional("2")")
</details>
<details><summary>:x: XCTest failed: StudentUnitTests/AssignmentRemindersInteractorLiveTests/testErrorOnDuplicateReminders</summary>


    XCTAssertEqual failed: ("nil") is not equal to ("Optional(Student.AssignmentReminderError.duplicate)")
    XCTAssertEqual failed: ("2") is not equal to ("1")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0792c3349d8c4cd200e701d63c103123d400df14
</p>

2024-11-15 14:08 UTC, szabinst requested changes
Using my account I came across some problems: 
- "Test" course "Chapter - 3" module, "Mp - Test": 
    - On simulator the file is added, I can submit it but I'd expect to state to change to "Resubmit Assignment" 
    - On physical device when I select a file, it doesn't do anything. 
    
- "Test" course "Chapter - 1" module, "Learn How to Write Assignments": 
    - When I tap "Submit  Assignment" the button animates out but nothing else happens. 

https://github.com/user-attachments/assets/056d71ac-75d7-4f1a-a765-3c4e90ce6f27

https://github.com/user-attachments/assets/d6b9e8af-141f-4a9b-a843-a663a6000028

2024-11-17 18:13 UTC, Ahmed-Naguib93 commented
> Using my account I came across some problems:
> 
> * "Test" course "Chapter - 3" module, "Mp - Test":
>   
>   * On simulator the file is added, I can submit it but I'd expect to state to change to "Resubmit Assignment"
>   * On physical device when I select a file, it doesn't do anything.
> * "Test" course "Chapter - 1" module, "Learn How to Write Assignments":
>   
>   * When I tap "Submit  Assignment" the button animates out but nothing else happens.
> 
>  ScreenRecording_11-15-2024.14-58-10_1.MP4 
>  ScreenRecording_11-15-2024.15-03-37_1.MP4

- Yes in the upload files not working, sorry i tested only on simulator, now is fixed.
- In text entry please check your account you did't select submission type is text entry.

2024-11-18 11:34 UTC, Ahmed-Naguib93 commented on Horizon/Horizon/Sources/Features/AssignmentDetails/View/Submission/AssignmentSubmissionView.swift
> +    @Bindable var viewModel: AssignmentDetailsViewModel
To can bind with $viewModel.textEntry

2024-11-18 11:45 UTC, Ahmed-Naguib93 commented on Horizon/Horizon/Sources/Features/AssignmentDetails/View/AssignmentDetails.swift
> +    @State private var viewModel: AssignmentDetailsViewModel
Yes, but in this case i set @State because i bind with show error alert  .alert("Error", isPresented: $viewModel.isShowAlertVisible)

2024-11-18 15:03 UTC, szabinst commented on Horizon/Horizon/Sources/Features/AssignmentDetails/View/AssignmentDetails.swift
> +    @State private var viewModel: AssignmentDetailsViewModel
You either need to mark the view model with @Bindable or create a Binding<Bool> computed property inside the view model. Please do a research on which one is the preferred way.

2024-11-18 15:03 UTC, szabinst commented on Horizon/Horizon/Sources/Features/AssignmentDetails/View/Submission/AssignmentSubmissionView.swift
> +    @Bindable var viewModel: AssignmentDetailsViewModel
Same as above Bindable view model vs binding computed property theory as above.

2024-11-19 11:09 UTC, szabinst approved these changes

2024-11-19 12:28 UTC, szabinst approved these changes

2024-11-19 12:28 UTC, merged