[Horizon] Add completion checkmark
instructure/canvas-ios pull request #2997
Opened 2024-12-03 15:01 UTC by Ahmed-Naguib93

Add module completion checkmark
https://instructure.atlassian.net/browse/CLX-149

2024-12-03 15:09 UTC, inst-danger commented
<details><summary>Horizon Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2F4b523279cf988641%2Fpublic-install-page%2F021333b107a527dc15b122d7c8b82fb7&size=150x150" />
</details>


<!-- HorizonBuild -->

2024-12-03 15:15 UTC, inst-danger commented
<!--
  0 failure: 
  2 warning:  One or more files..., The total test co...
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>One or more files are below the minimum test coverage 50%</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>The total test coverage is below the minimum 90%</td>
    </tr>
  </tbody>
</table>


Coverage | New % | Master % | Delta
-------- | ----- | -------- | -----
**Canvas iOS** | 89.99% | 90.05% | -0.06%
Core/Core/Courses/CourseProgression/CDCourseProgression.swift | 0% | -- | --
Core/Core/Planner/CalendarMain/ViewModel/PlannerViewModel.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarMain/Model/CalendarWeek.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarMain/View/Calendar/CalendarCardInteractionState.swift | 0% | 0% | 0%
Core/Core/Courses/CourseProgression/GetCoursesProgressionRequest.swift | 0% | -- | --
Core/Core/Planner/CalendarMain/Model/PlannablesInteractor.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarMain/View/Calendar/ViewPreferences.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarMain/Model/CalendarDay.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarMain/Model/CalendarMonth.swift | 0% | 0% | 0%
Core/Core/Planner/CalendarMain/View/Calendar/CalendarUtils.swift | 0% | 0% | 0%
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b5f8dc73cb9c2c72de086ebe6a78b0c82bfda54a
</p>

2024-12-04 14:04 UTC, szabinst requested changes
LGTM functionality wise!

2024-12-04 14:29 UTC, Ahmed-Naguib93 commented on Horizon/Horizon/Sources/Common/View/ExpandingModuleView.swift
> +#if DEBUG
Removed

2024-12-04 14:30 UTC, Ahmed-Naguib93 commented on Horizon/Horizon/Sources/Common/View/ProgramItemOverdueView.swift
> +#if DEBUG
Removed

2024-12-04 14:53 UTC, szabinst approved these changes

2024-12-04 14:54 UTC, merged