New Quiz LTI labeling
instructure/canvas-ios pull request #2999
Opened 2024-12-04 09:59 UTC by rh12

refs: [MBL-17960](https://instructure.atlassian.net/browse/MBL-17960)
affects: Student, Teacher, Parent
release note: none

## What's new
New Quizes should look like quizes, see ticket for details.
Also updated at some additional places:
- Modules screen
- Assignments screen
- Grades screen
- ToDo screen
- People Details screen
- PARENT app: Grades tab

## What's not changed
- Notifications screen
  - not updated, because `users/self/activity_stream` doesn't provide details
  - we could check via `html_url` which contains `assignmentID`, see `ActivityStreamViewController`
  - not sure it's worth it
- Calendar Events list
  - not updated, because `planner/items` doesn't provide details
  - we could check `plannable_id` when `plannable_type` is `assignment`, see `Plannable.iconImage`
  - not sure it's worth it

## Test plan
See ticket and above changed/not changed list.
Also smoke test for other type of assignments.

## TODO:
- unit tests
- screenshots

--- edit or delete this section ---
## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="" maxHeight=500></td>
<td><img src="" maxHeight=500></td>
</tr>
</table>

## Checklist
- [ ] Follow-up e2e test ticket created
- [ ] A11y checked
- [ ] Tested on phone
- [ ] Tested on tablet
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2024-12-04 10:06 UTC, inst-danger commented
<details><summary>Parent Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2F721db74163e71e29%2Fpublic-install-page%2Ffab0260c1fff97c98c6260790d4bd95b&size=150x150" />
</details>


<!-- ParentBuild -->

2024-12-04 10:07 UTC, inst-danger commented
<details><summary>Teacher Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2F3b6c07c029e18aab%2Fpublic-install-page%2F8bcd2c6c0f2f01a33ff7212027920170&size=150x150" />
</details>


<!-- TeacherBuild -->

2024-12-04 10:07 UTC, inst-danger commented
<details><summary>Student Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2F886d5037dff0db10%2Fpublic-install-page%2Fc94fa09d51d1a8a9c635847648f61abf&size=150x150" />
</details>


<!-- StudentBuild -->

2024-12-04 10:12 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  1 warning:  This pull request...
  
  3 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This pull request will not generate a release note.</td>
    </tr>
  </tbody>
</table>


#### Affected Apps: Student, Teacher, Parent

[MBL-17960](https://instructure.atlassian.net/browse/MBL-17960)

<details><summary>:x: Swift lint</summary>


    
    ----- xcbeautify -----
    Version: 2.11.0
    ----------------------
    
    ❌ /Users/vagrant/git/Core/CoreTests/Assignments/AssignmentTests.swift:416:1: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    /Users/vagrant/git/Core/CoreTests/Modules/ModuleItemTests.swift:96:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    /Users/vagrant/git/Core/CoreTests/Modules/ModuleItemTests.swift:99:1: error: Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0c52e99600b6e4c2f5949e12087ce1e79c94ca86
</p>

2024-12-04 13:00 UTC, suhaibabsi-inst reviewed
Thanks @rh12 !

Code +1

With minor notes to consider.

2024-12-04 14:21 UTC, suhaibabsi-inst requested changes
Tested on iPhone, I was able to see the new labeling reflected as described in the PR description. Beside button is showing the correct label on all details screens of Quiz.

One issue through, is that questions count label doesn't show on Assignments screen. And it shows count 0 for new quizzes on Quizzes screen.

![Simulator Screenshot - iPhone 16 - 2024-12-04 at 17 07 24](https://github.com/user-attachments/assets/c6c4132c-55de-4d81-a7e6-57ea6b4caf2f)

![Simulator Screenshot - iPhone 16 - 2024-12-04 at 17 07 00](https://github.com/user-attachments/assets/55b734a0-5f00-4d16-8afd-5cf1a4b7b687)

Still would need to test that on iPad as well.

2024-12-04 15:58 UTC, rh12 commented
> One issue through, is that questions count label doesn't show on Assignments screen. And it shows count 0 for new quizzes on Quizzes screen.

It is not displayed for Classic Quizzes either, so I would consider it a separate feature.
It seems to me the PR about Assignment List doesn't contain this either.
To be honest I'm not sure that this is something we want there, since it's also not listed on the Grades screen as well, which is a kind of "inspiration" for the new Assigmnets screen.
Feel free to bring it up as an improvement though, and discuss with UX/Product.

2024-12-04 16:05 UTC, vargaat requested changes

2024-12-04 17:08 UTC, rh12 commented on Core/Core/Modules/ModuleList/ModuleItemCell.swift
> +        }
Moving the `type` calculation to a private extension var `displayedType`

2024-12-04 17:08 UTC, rh12 commented on Core/Core/Modules/ModuleList/ModuleItemCell.swift
> +            item.isQuizLTI ? ModuleItemType.quiz("").label : item.type?.label,
Moving the `type` calculation to a private extension var `displayedType`

2024-12-04 17:10 UTC, rh12 commented on Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift
> +    }
I would avoid further littering the model type with view related properties. This should probably live in the related ViewModel, but we don't have one here.
As a lesser evil, I'm moving this to a private extension.

2024-12-04 17:20 UTC, rh12 commented on Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
> +        <attribute name="isQuizLTI" optional="YES" attributeType="Boolean" usesScalarValueType="YES"/>
Removing it, both for `Assignment` and `ModuleItem`

2024-12-04 21:25 UTC, suhaibabsi-inst approved these changes
@rh12 

I got confused with what's shown on the Figma file. If time permits, let's fix the count number issue on Quizzes screen. So, to match with what we have for old quizzes.

Approving so not to block the merge.

2024-12-04 22:54 UTC, rh12 commented
@suhaibabsi-inst 
> If time permits, let's fix the count number issue on Quizzes screen. So, to match with what we have for old quizzes.

Sorry, I overlooked this one in your previous comment. You're right, zero is not good here.
It turns out backend doesn't send a `question_count` for QuizLTIs, it's also not visible on the web.
But the web hides the Question count text altogether in this case, so I did the same.

2024-12-05 08:06 UTC, vargaat requested changes
Looks like we have a CoreData validation error when downloading modules.
![IMG_0427](https://github.com/user-attachments/assets/23ccc9f2-f007-4451-9c9e-df72db0bc07d)

2024-12-05 10:06 UTC, rh12 commented
@vargaat 
> Looks like we have a CoreData validation error when downloading modules.

Thanks for the fix!
QA+1 on this on my side, too

2024-12-05 10:52 UTC, suhaibabsi-inst submitted a review, later dismissed
QA +1

2024-12-05 12:38 UTC, vargaat submitted a review, later dismissed
QA+1

2024-12-05 13:35 UTC, ndrsszsz approved these changes

2024-12-05 13:35 UTC, suhaibabsi-inst approved these changes
QA +1

2024-12-05 13:40 UTC, merged