[Horizon] Tooltip
instructure/canvas-ios pull request #3026
Opened 2024-12-12 22:48 UTC by reabbotted

<img width="606" alt="Screenshot 2024-12-12 at 3 47 50 PM" src="https://github.com/user-attachments/assets/50f3b900-4cd4-48fd-85d1-988074119927" />
<img width="606" alt="Screenshot 2024-12-12 at 3 47 53 PM" src="https://github.com/user-attachments/assets/e06f926d-1a5f-4cd6-bb5b-928fc8124766" />

2024-12-13 13:39 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/AssignmentCellViewModelTests/testSubmissionStatusAndIconAndColor</summary>


    XCTAssertEqual failed: ("#6a7883") is not equal to ("#697783")
    XCTAssertEqual failed: ("#03893d") is not equal to ("#03893c")
</details>
<details><summary>:x: XCTest failed: CoreTests/CourseSyncCleanupInteractorTests/testApplicationOfflineDirectoryForUserDeleted</summary>


    XCTAssertFalse failed
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6dec10cf8cff081f49ae4eedf0905078209c784d
</p>

2024-12-13 13:43 UTC, Ahmed-Naguib93 commented
I have checked that the primary and secondary buttons are working fine, but the rest of the buttons are not clickable.

2024-12-13 14:20 UTC, szabinst requested changes
Like the view modifier approach! 

See my findings below.

2024-12-13 16:19 UTC, reabbotted commented on packages/HorizonUI/Sources/HorizonUI/Sources/Components/Tooltip/HorizonUI.Tooltip.swift
> +        struct Tooltip<TooltipContent: View>: ViewModifier {
I ended up removing the enum Tootip declaration. It's now just HorizonUI.Tooltip as it should have been.

2024-12-13 17:05 UTC, szabinst submitted a review, later dismissed

2024-12-13 20:12 UTC, reabbotted commented
There is a bug in iOS before 18.1 that doesn't honor the edge direction.

<img width="959" alt="Screenshot 2024-12-13 at 1 12 24 PM" src="https://github.com/user-attachments/assets/2a47bda1-e8e9-4ae3-ad4c-1859a36f5189" />

2024-12-16 10:00 UTC, inst-danger commented
<details><summary>Horizon Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2Fe04421413ae1e3a8%2Fpublic-install-page%2F64a797c8c80ffa4933fe22d108c4ecc3&size=150x150" />
</details>


<!-- HorizonBuild -->

2024-12-16 10:18 UTC, szabinst approved these changes

2024-12-16 10:18 UTC, merged