[Horizon] Update CourseDetails screen
instructure/canvas-ios pull request #3044
Opened 2024-12-28 16:26 UTC by Ahmed-Naguib93

1- [Create tab selector component](https://instructure.atlassian.net/browse/CLX-284)
2- [ Update CourseDetails screen](https://instructure.atlassian.net/browse/CLX-150)
3- [Create ModuleContainer](https://instructure.atlassian.net/browse/CLX-314)
4- [Create Module item Card](https://instructure.atlassian.net/browse/CLX-315)
**Note:**
I set some comments need to double check this the team 
https://github.com/user-attachments/assets/cc8f85ce-f200-4774-94f1-61dc50fce44f

2024-12-28 16:35 UTC, inst-danger commented
<details><summary>Horizon Build QR Code:</summary>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F88a3641e29e4745c%2Finstallable-artifacts%2Fc49c4b99851acc15%2Fpublic-install-page%2F026d4db9c641183dbd59a71155a5118c&size=150x150" />
</details>


<!-- HorizonBuild -->

2024-12-28 16:40 UTC, inst-danger commented
<!--
  1 failure:  Build failed, ski...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Build failed, skipping coverage check</td>
    </tr>
  </tbody>
</table>



<details><summary>:x: XCTest failed: CoreTests/AssignmentCellViewModelTests/testSubmissionStatusAndIconAndColor</summary>


    XCTAssertEqual failed: ("#6a7883") is not equal to ("#697783")
    XCTAssertEqual failed: ("#03893d") is not equal to ("#03893c")
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 853042574805cf75721c7b695a40518639728a60
</p>

2025-01-08 15:22 UTC, szabinst requested changes
The whole screen looks much better! 

Left some comments below.

2025-01-08 15:22 UTC, szabinst commented on packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleItemCard/HorizonUI.ModuleItemCard.Storybook.swift
Let's call this `LearningObjectItem` as in Figma.

2025-01-08 15:22 UTC, szabinst commented on packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleItemCard/HorizonUI.ModuleItemCard.Type.swift
> +            case .discussion: return "Discussion"
Let's use `String(localized:)`

2025-01-08 15:22 UTC, szabinst commented on packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleItemCard/HorizonUI.ModuleItemCard.swift
> +                        .resizable()
Pill has been modified so we can use it.

2025-01-08 15:22 UTC, szabinst commented on packages/HorizonUI/Sources/HorizonUI/Sources/Components/Tabs/HorizonUI.Tabs.Storybook.swift
Let's align the tabs below the title like `Badge` and `Spinner`.

2025-01-08 15:22 UTC, szabinst commented on packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleItemCard/HorizonUI.ModuleItemCard.Storybook.swift
> +    }
This is not needed.

2025-01-08 15:34 UTC, Ahmed-Naguib93 commented on packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleItemCard/HorizonUI.ModuleItemCard.Storybook.swift
> +    }
Oops,

2025-01-09 13:06 UTC, szabinst approved these changes

2025-01-09 13:06 UTC, merged